-- BACK TO 2000 V0.3.2 KOREAN FEATURE PHONES AND IMAGE AUDIT
--> statement-breakpoint
INSERT INTO brands (id, slug, name, description, status, created_at, updated_at) VALUES ('brand-399f01e13e37', 'motorola', 'Motorola', '', 'published', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, status='published', updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO content_items (id, type, slug, name, eyebrow, summary, body, start_year, end_year, brand_id, category_id, accent, status, quality_status, featured, metadata, content_version, verified_at, published_at, created_at, updated_at) VALUES ('phone-motorola-startac-st7760', 'phone', 'motorola-startac-st7760', 'Motorola StarTAC ST7760', '주머니에 들어간 CDMA 스타택', '88g대 초경량 폴더 구조로 국내 휴대전화의 크기와 디자인 경쟁을 앞당긴 디지털 StarTAC', 'ST7760은 아날로그 StarTAC의 상징적인 접이식 구조를 CDMA 방식으로 옮긴 국내 정식 출시 모델입니다. 작은 몸체와 긴 대기시간을 내세워 휴대전화를 과시용 장비에서 일상적으로 지니는 물건으로 바꿨습니다.', 1998, NULL, 'brand-399f01e13e37', 'category-phone', '#504840', 'published', 'verified', 1, '{"highlights":["CDMA 디지털 방식","초소형 폴더 구조","국내 130만 대 이상 판매"],"specs":{"제조사":"Motorola","국내출시":"1998년 10월","형태":"폴더","무게":"약 88~99g"},"story":{"significance":"1996년 시작된 StarTAC 디자인을 국내 CDMA 환경에 맞춰 확장해, 1990년대 후반 휴대전화 경량화와 폴더형 경쟁을 촉발한 상징적인 제품입니다.","legacy":"한 손으로 열고 닫는 폴더폰 문법은 2000년대 피처폰의 표준이 되었고, 오늘날 플립형 폴더블 스마트폰에서도 그 기억이 다시 해석되고 있습니다."}}', 3, 1786579200000, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug, name=excluded.name, eyebrow=excluded.eyebrow, summary=excluded.summary, body=excluded.body, start_year=excluded.start_year, brand_id=excluded.brand_id, category_id='category-phone', accent=excluded.accent, status='published', quality_status='verified', featured=excluded.featured, metadata=excluded.metadata, content_version=3, verified_at=excluded.verified_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_years (content_id, year, sort_order) VALUES ('phone-motorola-startac-st7760', 1998, 0);
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-399f01e13e37', 'tag-399f01e13e37', 'Motorola', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-motorola-startac-st7760', 'tag-399f01e13e37');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-271cb3940e11', 'tag-271cb3940e11', 'StarTAC', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-motorola-startac-st7760', 'tag-271cb3940e11');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-00b4c3addae4', 'tag-00b4c3addae4', 'CDMA', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-motorola-startac-st7760', 'tag-00b4c3addae4');
--> statement-breakpoint
INSERT INTO content_sources (id, content_id, label, url, source_type, is_primary, checked_at, created_at, updated_at) VALUES ('source-v032-95e0f4059290', 'phone-motorola-startac-st7760', '전자신문 국내 출시 기록', 'https://www.etnews.com/199809240132', 'editorial', 1, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET label=excluded.label, url=excluded.url, checked_at=excluded.checked_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-5cb32285c18e', '/images/archive/devices/motorola-startac-st7760.jpg', '/images/archive/devices/motorola-startac-st7760.jpg', 'static', 'motorola-startac-st7760.jpg', 'image/jpeg', 400268, '검은색 Motorola StarTAC 7760을 펼쳐 화면과 숫자 키패드를 보인 제품 사진', 'eBay product archive', 'https://www.ebay.fr/itm/256575609548', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-motorola-startac-st7760' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-motorola-startac-st7760', 'media-5cb32285c18e', 'hero', 0);
--> statement-breakpoint
INSERT OR IGNORE INTO content_revisions (id, content_id, version, snapshot, note, created_at) VALUES ('revision-v032-95e0f4059290', 'phone-motorola-startac-st7760', 3, '{"name":"Motorola StarTAC ST7760","summary":"88g대 초경량 폴더 구조로 국내 휴대전화의 크기와 디자인 경쟁을 앞당긴 디지털 StarTAC","description":"ST7760은 아날로그 StarTAC의 상징적인 접이식 구조를 CDMA 방식으로 옮긴 국내 정식 출시 모델입니다. 작은 몸체와 긴 대기시간을 내세워 휴대전화를 과시용 장비에서 일상적으로 지니는 물건으로 바꿨습니다.","specs":{"제조사":"Motorola","국내출시":"1998년 10월","형태":"폴더","무게":"약 88~99g"},"story":{"significance":"1996년 시작된 StarTAC 디자인을 국내 CDMA 환경에 맞춰 확장해, 1990년대 후반 휴대전화 경량화와 폴더형 경쟁을 촉발한 상징적인 제품입니다.","legacy":"한 손으로 열고 닫는 폴더폰 문법은 2000년대 피처폰의 표준이 되었고, 오늘날 플립형 폴더블 스마트폰에서도 그 기억이 다시 해석되고 있습니다."},"source":{"label":"전자신문 국내 출시 기록","url":"https://www.etnews.com/199809240132"},"image":{"src":"/images/archive/devices/motorola-startac-st7760.jpg","alt":"검은색 Motorola StarTAC 7760을 펼쳐 화면과 숫자 키패드를 보인 제품 사진","credit":"eBay product archive","sourceUrl":"https://www.ebay.fr/itm/256575609548","license":"원저작자 권리 보유 · 출처 표기"}}', 'v0.3.2 Korean feature phone archive', 1786579200000);
--> statement-breakpoint
INSERT INTO brands (id, slug, name, description, status, created_at, updated_at) VALUES ('brand-90e01d646458', 'samsung', 'Samsung', '', 'published', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, status='published', updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO content_items (id, type, slug, name, eyebrow, summary, body, start_year, end_year, brand_id, category_id, accent, status, quality_status, featured, metadata, content_version, verified_at, published_at, created_at, updated_at) VALUES ('phone-anycall-sch-v500', 'phone', 'anycall-sch-v500', 'Anycall SCH-V500', '화면을 돌린 가로본능', '세로 화면이라는 상식을 깨고 LCD를 가로로 회전시킨 메가픽셀 VOD 폴더폰', 'SCH-V500은 폴더를 연 뒤 화면을 90도로 돌려 사진과 VOD를 가로로 볼 수 있게 만든 애니콜입니다. 2.2인치 QVGA 화면, 메가픽셀 카메라, MP3와 3D 게임을 한 기기에 담았습니다.', 2004, NULL, 'brand-90e01d646458', 'category-phone', '#94a3b8', 'published', 'verified', 1, '{"highlights":["90도 회전 LCD","메가픽셀 사진·동영상","MP3·3D 게임"],"specs":{"제조사":"삼성전자","출시":"2004년 8월","형태":"스위블 폴더","가격":"70만원대"},"story":{"significance":"영상은 가로로 본다는 사용 습관을 휴대전화 폼팩터에 직접 반영해, 기능과 외형이 함께 경험을 설계할 수 있음을 보여준 제품입니다.","legacy":"회전·폴더·듀얼 스크린으로 이어진 실험적 폼팩터의 선례가 되었고, 모바일 영상 감상이 제품 형태를 바꾸는 흐름을 일찍 보여줬습니다."}}', 3, 1786579200000, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug, name=excluded.name, eyebrow=excluded.eyebrow, summary=excluded.summary, body=excluded.body, start_year=excluded.start_year, brand_id=excluded.brand_id, category_id='category-phone', accent=excluded.accent, status='published', quality_status='verified', featured=excluded.featured, metadata=excluded.metadata, content_version=3, verified_at=excluded.verified_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_years (content_id, year, sort_order) VALUES ('phone-anycall-sch-v500', 2004, 0);
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-6cd8f39f8360', 'tag-6cd8f39f8360', '애니콜', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-anycall-sch-v500', 'tag-6cd8f39f8360');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-1f8f6742848a', 'tag-1f8f6742848a', '가로본능', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-anycall-sch-v500', 'tag-1f8f6742848a');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-3bf5d3b89dd8', 'tag-3bf5d3b89dd8', '카메라폰', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-anycall-sch-v500', 'tag-3bf5d3b89dd8');
--> statement-breakpoint
INSERT INTO content_sources (id, content_id, label, url, source_type, is_primary, checked_at, created_at, updated_at) VALUES ('source-v032-25394ac3fe40', 'phone-anycall-sch-v500', 'Samsung Newsroom 출시 기록', 'https://news.samsung.com/kr/%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-%EA%B0%80%EB%A1%9C%ED%99%94%EB%A9%B4-%EB%A9%94%EA%B0%80%ED%94%BD%EC%85%80vod%ED%8F%B0-%EC%B6%9C%EC%8B%9C', 'editorial', 1, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET label=excluded.label, url=excluded.url, checked_at=excluded.checked_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-7246f4e92ac9', '/images/archive/devices/samsung-sch-v500.png', '/images/archive/devices/samsung-sch-v500.png', 'static', 'samsung-sch-v500.png', 'image/png', 478200, 'Anycall SCH-V500의 닫힌 모습과 화면을 가로로 돌려 연 모습', 'Samsung Electronics / Danawa DPG', 'https://dpg.danawa.com/mobile/news/view?boardSeq=64&listSeq=5329940', '역사 기록용 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-anycall-sch-v500' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-anycall-sch-v500', 'media-7246f4e92ac9', 'hero', 0);
--> statement-breakpoint
INSERT OR IGNORE INTO content_revisions (id, content_id, version, snapshot, note, created_at) VALUES ('revision-v032-25394ac3fe40', 'phone-anycall-sch-v500', 3, '{"name":"Anycall SCH-V500","summary":"세로 화면이라는 상식을 깨고 LCD를 가로로 회전시킨 메가픽셀 VOD 폴더폰","description":"SCH-V500은 폴더를 연 뒤 화면을 90도로 돌려 사진과 VOD를 가로로 볼 수 있게 만든 애니콜입니다. 2.2인치 QVGA 화면, 메가픽셀 카메라, MP3와 3D 게임을 한 기기에 담았습니다.","specs":{"제조사":"삼성전자","출시":"2004년 8월","형태":"스위블 폴더","가격":"70만원대"},"story":{"significance":"영상은 가로로 본다는 사용 습관을 휴대전화 폼팩터에 직접 반영해, 기능과 외형이 함께 경험을 설계할 수 있음을 보여준 제품입니다.","legacy":"회전·폴더·듀얼 스크린으로 이어진 실험적 폼팩터의 선례가 되었고, 모바일 영상 감상이 제품 형태를 바꾸는 흐름을 일찍 보여줬습니다."},"source":{"label":"Samsung Newsroom 출시 기록","url":"https://news.samsung.com/kr/%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90-%EA%B0%80%EB%A1%9C%ED%99%94%EB%A9%B4-%EB%A9%94%EA%B0%80%ED%94%BD%EC%85%80vod%ED%8F%B0-%EC%B6%9C%EC%8B%9C"},"image":{"src":"/images/archive/devices/samsung-sch-v500.png","alt":"Anycall SCH-V500의 닫힌 모습과 화면을 가로로 돌려 연 모습","credit":"Samsung Electronics / Danawa DPG","sourceUrl":"https://dpg.danawa.com/mobile/news/view?boardSeq=64&listSeq=5329940","license":"역사 기록용 · 출처 표기"}}', 'v0.3.2 Korean feature phone archive', 1786579200000);
--> statement-breakpoint
INSERT INTO brands (id, slug, name, description, status, created_at, updated_at) VALUES ('brand-b0fcd51c4f2e', 'pantech-curitel', 'Pantech&Curitel', '', 'published', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, status='published', updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO content_items (id, type, slug, name, eyebrow, summary, body, start_year, end_year, brand_id, category_id, accent, status, quality_status, featured, metadata, content_version, verified_at, published_at, created_at, updated_at) VALUES ('phone-curitel-ph-s3500', 'phone', 'curitel-ph-s3500', 'Curitel PH-S3500', '동그란 3D 게임폰', '원형 폴더와 전용 그래픽 칩으로 휴대전화를 손안의 게임기로 해석한 큐리텔', 'PH-S3500은 원형 상판과 양손 조작용 방향·슈팅 버튼, 별도 3D 그래픽 가속칩을 결합한 피처폰입니다. MP3와 카메라까지 더해 모바일 엔터테인먼트 기기를 지향했습니다.', 2004, NULL, 'brand-b0fcd51c4f2e', 'category-phone', '#b7a48d', 'published', 'verified', 0, '{"highlights":["3D 그래픽 가속칩","양손 게임 조작 버튼","듀얼 스피커와 MP3"],"specs":{"제조사":"팬택&큐리텔","출시":"2004년 10월","형태":"원형 폴더","화면":"2.1인치 와이드 LCD"},"story":{"significance":"통화 중심 설계를 벗어나 특정 취미인 게임에 맞춰 외형과 버튼 배치를 바꾼 국내 피처폰 시대의 대담한 실험입니다.","legacy":"전용 게임폰은 주류가 되지 못했지만, 고성능 모바일 GPU와 게임 전용 액세서리·게이밍폰으로 이어지는 발상을 앞서 보여줬습니다."}}', 3, 1786579200000, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug, name=excluded.name, eyebrow=excluded.eyebrow, summary=excluded.summary, body=excluded.body, start_year=excluded.start_year, brand_id=excluded.brand_id, category_id='category-phone', accent=excluded.accent, status='published', quality_status='verified', featured=excluded.featured, metadata=excluded.metadata, content_version=3, verified_at=excluded.verified_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_years (content_id, year, sort_order) VALUES ('phone-curitel-ph-s3500', 2004, 0);
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-1b42f3996bf0', 'tag-1b42f3996bf0', '큐리텔', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-curitel-ph-s3500', 'tag-1b42f3996bf0');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-feecef5e1225', 'tag-feecef5e1225', '게임폰', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-curitel-ph-s3500', 'tag-feecef5e1225');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-3a1805781ddb', 'tag-3a1805781ddb', '피처폰', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-curitel-ph-s3500', 'tag-3a1805781ddb');
--> statement-breakpoint
INSERT INTO content_sources (id, content_id, label, url, source_type, is_primary, checked_at, created_at, updated_at) VALUES ('source-v032-914c2fdb64bb', 'phone-curitel-ph-s3500', '전자신문 출시 보도', 'https://www.etnews.com/200409300156', 'editorial', 1, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET label=excluded.label, url=excluded.url, checked_at=excluded.checked_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-120ce1ed7d4d', '/images/archive/devices/curitel-ph-s3500.jpg', '/images/archive/devices/curitel-ph-s3500.jpg', 'static', 'curitel-ph-s3500.jpg', 'image/jpeg', 37064, '원형 외부 화면을 갖춘 은색 Curitel PH-S3500 제품 정면', 'Bunjang 판매자 제공 이미지', 'https://globalbunjang.com/product/333330999', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-curitel-ph-s3500' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-curitel-ph-s3500', 'media-120ce1ed7d4d', 'hero', 0);
--> statement-breakpoint
INSERT OR IGNORE INTO content_revisions (id, content_id, version, snapshot, note, created_at) VALUES ('revision-v032-914c2fdb64bb', 'phone-curitel-ph-s3500', 3, '{"name":"Curitel PH-S3500","summary":"원형 폴더와 전용 그래픽 칩으로 휴대전화를 손안의 게임기로 해석한 큐리텔","description":"PH-S3500은 원형 상판과 양손 조작용 방향·슈팅 버튼, 별도 3D 그래픽 가속칩을 결합한 피처폰입니다. MP3와 카메라까지 더해 모바일 엔터테인먼트 기기를 지향했습니다.","specs":{"제조사":"팬택&큐리텔","출시":"2004년 10월","형태":"원형 폴더","화면":"2.1인치 와이드 LCD"},"story":{"significance":"통화 중심 설계를 벗어나 특정 취미인 게임에 맞춰 외형과 버튼 배치를 바꾼 국내 피처폰 시대의 대담한 실험입니다.","legacy":"전용 게임폰은 주류가 되지 못했지만, 고성능 모바일 GPU와 게임 전용 액세서리·게이밍폰으로 이어지는 발상을 앞서 보여줬습니다."},"source":{"label":"전자신문 출시 보도","url":"https://www.etnews.com/200409300156"},"image":{"src":"/images/archive/devices/curitel-ph-s3500.jpg","alt":"원형 외부 화면을 갖춘 은색 Curitel PH-S3500 제품 정면","credit":"Bunjang 판매자 제공 이미지","sourceUrl":"https://globalbunjang.com/product/333330999","license":"원저작자 권리 보유 · 출처 표기"}}', 'v0.3.2 Korean feature phone archive', 1786579200000);
--> statement-breakpoint
INSERT INTO brands (id, slug, name, description, status, created_at, updated_at) VALUES ('brand-01a396929fce', 'ktft-ever', 'KTFT EVER', '', 'published', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, status='published', updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO content_items (id, type, slug, name, eyebrow, summary, body, start_year, end_year, brand_id, category_id, accent, status, quality_status, featured, metadata, content_version, verified_at, published_at, created_at, updated_at) VALUES ('phone-ever-ktf-x7000', 'phone', 'ever-ktf-x7000', 'EVER KTF-X7000', '주머니 속 DJ폰', '128MB 메모리와 중저음 강화 이어폰으로 MP3폰 대중화를 겨냥한 EVER', 'KTF-X7000은 최대 약 25곡을 담는 128MB 메모리, 1.3메가픽셀 카메라와 중저음 강화 기능을 갖춘 폴더폰입니다. 고가 MP3폰이 많던 시기에 30만원 후반대 가격을 앞세웠습니다.', 2005, NULL, 'brand-01a396929fce', 'category-phone', '#9ca3af', 'published', 'verified', 0, '{"highlights":["128MB 내장 메모리","중저음 3단계 강화","1.3메가픽셀 카메라"],"specs":{"제조사":"KTFT","출시":"2005년 1월","형태":"폴더","가격":"30만원 후반대"},"story":{"significance":"휴대전화와 MP3 플레이어가 합쳐지던 시기에 음악 기능을 일부 고급형이 아닌 대중형 가격대로 끌어내린 제품입니다.","legacy":"휴대전화가 별도의 음악 재생기를 흡수한 흐름은 이후 스마트폰의 스트리밍·무선 이어폰 생태계로 확장됐습니다."}}', 3, 1786579200000, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug, name=excluded.name, eyebrow=excluded.eyebrow, summary=excluded.summary, body=excluded.body, start_year=excluded.start_year, brand_id=excluded.brand_id, category_id='category-phone', accent=excluded.accent, status='published', quality_status='verified', featured=excluded.featured, metadata=excluded.metadata, content_version=3, verified_at=excluded.verified_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_years (content_id, year, sort_order) VALUES ('phone-ever-ktf-x7000', 2005, 0);
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-f7561734ae1b', 'tag-f7561734ae1b', 'EVER', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-ever-ktf-x7000', 'tag-f7561734ae1b');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-3acb89b2a219', 'tag-3acb89b2a219', 'DJ폰', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-ever-ktf-x7000', 'tag-3acb89b2a219');
--> statement-breakpoint
INSERT INTO tags (id, slug, name, created_at, updated_at) VALUES ('tag-c1f3e0a984e1', 'tag-c1f3e0a984e1', 'MP3폰', 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET name=excluded.name, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT OR IGNORE INTO content_tags (content_id, tag_id) VALUES ('phone-ever-ktf-x7000', 'tag-c1f3e0a984e1');
--> statement-breakpoint
INSERT INTO content_sources (id, content_id, label, url, source_type, is_primary, checked_at, created_at, updated_at) VALUES ('source-v032-20b1a76d5169', 'phone-ever-ktf-x7000', 'KTFT 출시 보도', 'https://www.newswire.co.kr/newsRead.php?no=24920', 'editorial', 1, 1786579200000, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET label=excluded.label, url=excluded.url, checked_at=excluded.checked_at, updated_at=excluded.updated_at;
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-fe1a67780dad', '/images/archive/devices/ever-ktf-x7000.jpg', '/images/archive/devices/ever-ktf-x7000.jpg', 'static', 'ever-ktf-x7000.jpg', 'image/jpeg', 122330, '은색 EVER DJ KTF-X7000 폴더폰을 펼친 제품 모습', 'Bunjang 판매자 제공 이미지', 'https://globalbunjang.com/product/354687640', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-ever-ktf-x7000' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-ever-ktf-x7000', 'media-fe1a67780dad', 'hero', 0);
--> statement-breakpoint
INSERT OR IGNORE INTO content_revisions (id, content_id, version, snapshot, note, created_at) VALUES ('revision-v032-20b1a76d5169', 'phone-ever-ktf-x7000', 3, '{"name":"EVER KTF-X7000","summary":"128MB 메모리와 중저음 강화 이어폰으로 MP3폰 대중화를 겨냥한 EVER","description":"KTF-X7000은 최대 약 25곡을 담는 128MB 메모리, 1.3메가픽셀 카메라와 중저음 강화 기능을 갖춘 폴더폰입니다. 고가 MP3폰이 많던 시기에 30만원 후반대 가격을 앞세웠습니다.","specs":{"제조사":"KTFT","출시":"2005년 1월","형태":"폴더","가격":"30만원 후반대"},"story":{"significance":"휴대전화와 MP3 플레이어가 합쳐지던 시기에 음악 기능을 일부 고급형이 아닌 대중형 가격대로 끌어내린 제품입니다.","legacy":"휴대전화가 별도의 음악 재생기를 흡수한 흐름은 이후 스마트폰의 스트리밍·무선 이어폰 생태계로 확장됐습니다."},"source":{"label":"KTFT 출시 보도","url":"https://www.newswire.co.kr/newsRead.php?no=24920"},"image":{"src":"/images/archive/devices/ever-ktf-x7000.jpg","alt":"은색 EVER DJ KTF-X7000 폴더폰을 펼친 제품 모습","credit":"Bunjang 판매자 제공 이미지","sourceUrl":"https://globalbunjang.com/product/354687640","license":"원저작자 권리 보유 · 출처 표기"}}', 'v0.3.2 Korean feature phone archive', 1786579200000);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-8135cc291c42', '/images/archive/devices/samsung-sch-800-product.webp', '/images/archive/devices/samsung-sch-800-product.webp', 'static', 'samsung-sch-800-product.webp', 'image/webp', 39000, '검은색 Samsung Anycall SCH-800 폴더형 휴대전화의 닫힌 제품 모습', 'Bunjang 판매자 제공 이미지', 'https://globalbunjang.com/product/338954832', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-samsung-sch800' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-samsung-sch800', 'media-8135cc291c42', 'hero', 0);
--> statement-breakpoint
UPDATE content_items SET body='1998년 출시된 SCH-800은 삼성 휴대전화 디자인이 바 타입에서 폴더형으로 이동하던 장면을 보여줍니다.', metadata='{"highlights":["컴팩트 폴더 구조","CDMA 휴대전화","초기 애니콜 디자인"],"specs":{"제조사":"삼성전자","출시":"1998년","형태":"폴더"},"story":{"significance":"국내 CDMA 시장에서 애니콜의 존재감을 넓힌 초기 폴더형 모델로, 통화 기기였던 휴대전화가 몸에 지니는 디자인 제품으로 바뀌는 과정을 보여줍니다.","legacy":"이후 애니콜은 카메라·MP3·가로 화면 같은 기능을 폴더 구조 안에 결합했고, 그 계보는 Galaxy 시대의 모바일 디자인으로 이어졌습니다."}}', content_version=3, updated_at=1786579200000 WHERE id='phone-samsung-sch800';
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-bc7c7068d8f3', '/images/archive/devices/blackberry-pearl-8100-v032.jpg', '/images/archive/devices/blackberry-pearl-8100-v032.jpg', 'static', 'blackberry-pearl-8100-v032.jpg', 'image/jpeg', 12942, '소형 SureType 키보드와 트랙볼이 보이는 BlackBerry Pearl 8100 정면 제품', 'Newegg product archive', 'https://www.newegg.com/blackberry-pearl-2-2/p/N82E16875353043', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-blackberry-pearl' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-blackberry-pearl', 'media-bc7c7068d8f3', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-68436e7006af', '/images/archive/devices/blackberry-bold-9000-v032.jpg', '/images/archive/devices/blackberry-bold-9000-v032.jpg', 'static', 'blackberry-bold-9000-v032.jpg', 'image/jpeg', 83460, '풀 QWERTY 키보드와 중앙 트랙볼이 선명한 BlackBerry Bold 9000 제품', 'PhonesData product archive', 'https://phonesdata.com/en/smartphones/blackberry/bold-9000-153/', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-blackberry-bold' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-blackberry-bold', 'media-68436e7006af', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-884d61dfac37', '/images/archive/devices/blackberry-torch-9800-v032.jpg', '/images/archive/devices/blackberry-torch-9800-v032.jpg', 'static', 'blackberry-torch-9800-v032.jpg', 'image/jpeg', 150047, '세로 슬라이드를 열어 QWERTY 키보드를 드러낸 BlackBerry Torch 9800 제품', 'GSMOnline product review', 'https://gsmonline.pl/artykuly/blackberry-torch-9800-test-recenzja', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-blackberry-torch' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-blackberry-torch', 'media-884d61dfac37', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-31d06e81cd29', '/images/archive/devices/blackberry-key2-v032.png', '/images/archive/devices/blackberry-key2-v032.png', 'static', 'blackberry-key2-v032.png', 'image/png', 903808, '큰 터치 화면과 4열 물리 키보드가 모두 보이는 BlackBerry KEY2 정면 제품', 'KindPNG product image', 'https://www.kindpng.com/imgv/hwhwmhJ_blackberry-key2-hd-png-download/', '비상업적 사용 · 출처 표기', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-blackberry-key2' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-blackberry-key2', 'media-31d06e81cd29', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-f0f96963068a', '/images/archive/milestones/1998-paypal-mark.svg', '/images/archive/milestones/1998-paypal-mark.svg', 'static', '1998-paypal-mark.svg', 'image/svg+xml', 467, 'PayPal 결제 서비스 대표 마크', 'PayPal / Simple Icons contributors', 'https://simpleicons.org/?q=paypal', 'CC0 1.0 · trademark', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-1998-paypal' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-1998-paypal', 'media-f0f96963068a', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-550632d6e688', '/images/archive/milestones/2000-baidu-mark.svg', '/images/archive/milestones/2000-baidu-mark.svg', 'static', '2000-baidu-mark.svg', 'image/svg+xml', 1406, 'Baidu 검색 서비스 대표 마크', 'Baidu / Simple Icons contributors', 'https://simpleicons.org/?q=baidu', 'CC0 1.0 · trademark', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2000-baidu' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2000-baidu', 'media-550632d6e688', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-22857d90def9', '/images/archive/milestones/2013-vine-mark.svg', '/images/archive/milestones/2013-vine-mark.svg', 'static', '2013-vine-mark.svg', 'image/svg+xml', 1037, 'Vine 숏폼 동영상 서비스 대표 로고', 'Vine service mark', 'https://en.wikipedia.org/wiki/Vine_(service)', '상표 · 역사 기록용', 'review', 1, NULL, 1786579200000, 1786579200000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, rights_status=excluded.rights_status, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2013-vine' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2013-vine', 'media-22857d90def9', 'hero', 0);
--> statement-breakpoint
PRAGMA optimize;
