-- BACK TO 2000 IMAGE MAINTENANCE (NO VERSION RELEASE)
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-bb4aa0d29a08', '/images/archive/devices/curitel-ph-s3500-device.webp', '/images/archive/devices/curitel-ph-s3500-device.webp', 'static', 'curitel-ph-s3500-device.webp', 'image/webp', 51280, '원형 외부 화면과 카메라가 보이는 은색 Curitel PH-S3500 실물 제품', 'Bunjang 판매자 제공 이미지', 'https://globalbunjang.com/product/352203507', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-curitel-ph-s3500' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-curitel-ph-s3500', 'media-bb4aa0d29a08', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-545b61b02c74', '/images/archive/devices/samsung-anycall-haptic-device.webp', '/images/archive/devices/samsung-anycall-haptic-device.webp', 'static', 'samsung-anycall-haptic-device.webp', 'image/webp', 48636, 'Samsung Anycall Haptic SCH-W420의 화면 구성을 보여주는 실물 제품 사진', 'The Register product archive', 'https://www.theregister.com/2008/03/26/samsung_anycall_w420/', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-anycall-haptic' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-anycall-haptic', 'media-545b61b02c74', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-cd4bb9d65d3a', '/images/archive/devices/motorola-moto-x-style-device.webp', '/images/archive/devices/motorola-moto-x-style-device.webp', 'static', 'motorola-moto-x-style-device.webp', 'image/webp', 190302, '곡면 후면과 카메라 모듈이 선명한 Motorola Moto X Style 실물 제품', 'Kārlis Dambrāns / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Motorola_Moto_X_Style_(22033955888).jpg', 'CC BY 2.0', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='phone-moto-x-style' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('phone-moto-x-style', 'media-cd4bb9d65d3a', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-b6a9a8ca1852', '/images/archive/milestones/2002-blackberry-5810-device.webp', '/images/archive/milestones/2002-blackberry-5810-device.webp', 'static', '2002-blackberry-5810-device.webp', 'image/webp', 21624, '넓은 흑백 화면과 QWERTY 키보드를 갖춘 BlackBerry 5810 실물 제품', 'Mobile Phone Museum', 'https://www.mobilephonemuseum.com/phone-detail/blackbarry-5810', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2002-blackberry-5810' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2002-blackberry-5810', 'media-b6a9a8ca1852', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-95a509cf5893', '/images/archive/milestones/2003-blackberry-6210-device.webp', '/images/archive/milestones/2003-blackberry-6210-device.webp', 'static', '2003-blackberry-6210-device.webp', 'image/webp', 15570, '손에 든 파란색 BlackBerry 6210과 QWERTY 키보드가 보이는 실물 사진', 'BBRef device archive', 'https://bbref.ca/6210', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2003-blackberry-6210' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2003-blackberry-6210', 'media-95a509cf5893', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-f780890e902d', '/images/archive/milestones/2005-blackberry-8700-device.webp', '/images/archive/milestones/2005-blackberry-8700-device.webp', 'static', '2005-blackberry-8700-device.webp', 'image/webp', 29768, '컬러 화면과 QWERTY 키보드를 갖춘 BlackBerry 8700 실물 제품', 'PhoneMore product archive', 'https://www.phonemore.com/pictures/blackberry/8700/', '원저작자 권리 보유 · 출처 표기', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2005-blackberry-8700' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2005-blackberry-8700', 'media-f780890e902d', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-5c9b54e6ccee', '/images/archive/milestones/2009-bing-clean.png', '/images/archive/milestones/2009-bing-clean.png', 'static', '2009-bing-clean.png', 'image/png', 28782, '투명 배경에 정돈된 Microsoft Bing 로고', 'Microsoft / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Microsoft_Bing_logo.svg', 'Public domain text logo · trademark', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2009-bing' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2009-bing', 'media-5c9b54e6ccee', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-0b0e07338be9', '/images/archive/milestones/2009-iphone-3gs-device.webp', '/images/archive/milestones/2009-iphone-3gs-device.webp', 'static', '2009-iphone-3gs-device.webp', 'image/webp', 81336, '손에 든 검은색 Apple iPhone 3GS 실물 제품', 'William Hook / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:IPhone_3GS.jpg', 'CC BY-SA 2.0', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2009-iphone-3gs' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2009-iphone-3gs', 'media-0b0e07338be9', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-e2976144ce84', '/images/archive/milestones/2013-lg-g2-device.webp', '/images/archive/milestones/2013-lg-g2-device.webp', 'static', '2013-lg-g2-device.webp', 'image/webp', 91748, '화면과 전면 베젤이 선명한 검은색 LG G2 실물 제품', 'Wikimedia Commons contributor', 'https://commons.wikimedia.org/wiki/File:LG_G2_demo_phone.jpg', 'Wikimedia Commons license', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2013-lg-g2' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2013-lg-g2', 'media-e2976144ce84', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-1d507933f4d7', '/images/archive/milestones/2013-samsung-galaxy-s4-device.webp', '/images/archive/milestones/2013-samsung-galaxy-s4-device.webp', 'static', '2013-samsung-galaxy-s4-device.webp', 'image/webp', 296952, '화면을 켠 검은색 Samsung Galaxy S4 실물 제품', 'Wikimedia Commons contributor', 'https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S4_(Black_Mist)_-_Front.jpg', 'Wikimedia Commons license', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2013-samsung-galaxy-s4' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2013-samsung-galaxy-s4', 'media-1d507933f4d7', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-2dbb9524bc04', '/images/archive/milestones/2014-samsung-galaxy-s5-device.webp', '/images/archive/milestones/2014-samsung-galaxy-s5-device.webp', 'static', '2014-samsung-galaxy-s5-device.webp', 'image/webp', 19710, '전면 전체가 보이는 흰색 Samsung Galaxy S5 제품', 'Wikimedia Commons contributor', 'https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S5.png', 'Wikimedia Commons license', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2014-samsung-galaxy-s5' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2014-samsung-galaxy-s5', 'media-2dbb9524bc04', 'hero', 0);
--> statement-breakpoint
INSERT INTO media (id, object_key, public_url, storage_provider, filename, mime_type, byte_size, alt_text, credit, source_url, license, rights_status, attribution_required, verified_at, created_at, updated_at) VALUES ('media-3a0b87e0dfb2', '/images/archive/milestones/2016-google-pixel-device.webp', '/images/archive/milestones/2016-google-pixel-device.webp', 'static', '2016-google-pixel-device.webp', 'image/webp', 268938, '화면을 켠 1세대 Google Pixel과 Pixel XL 실물 제품', 'Wikimedia Commons contributor', 'https://commons.wikimedia.org/wiki/File:Google_Pixel_and_Pixel_XL_smartphones_(30155272575).jpg', 'Wikimedia Commons license', 'review', 1, NULL, 1786665600000, 1786665600000) ON CONFLICT(id) DO UPDATE SET public_url=excluded.public_url, object_key=excluded.object_key, filename=excluded.filename, mime_type=excluded.mime_type, byte_size=excluded.byte_size, alt_text=excluded.alt_text, credit=excluded.credit, source_url=excluded.source_url, license=excluded.license, updated_at=excluded.updated_at;
--> statement-breakpoint
DELETE FROM content_media WHERE content_id='milestone-2016-google-pixel' AND role='hero';
--> statement-breakpoint
INSERT INTO content_media (content_id, media_id, role, sort_order) VALUES ('milestone-2016-google-pixel', 'media-3a0b87e0dfb2', 'hero', 0);
--> statement-breakpoint
PRAGMA optimize;
