-- BACK TO 2000 v0.4.3 · complete the remaining editorial review queue
UPDATE content_items SET body='Daum은 1997년 한메일로 출발해 무료 웹메일, 다음 카페, 뉴스와 검색을 한 화면에 묶은 한국의 1세대 포털입니다. 개인 메일함과 관심사별 커뮤니티를 일상의 인터넷 습관으로 만들었고, 이후 지도·콘텐츠·모바일 서비스로 확장되며 오늘날 Kakao의 포털 축으로 이어졌습니다.', metadata=json_set(metadata,'$.story.significance','무료 웹메일과 카페를 결합해 인터넷을 정보 검색만이 아니라 사람을 만나고 관계를 유지하는 생활 공간으로 넓혔습니다.','$.story.legacy','한메일은 Daum 메일로, 다음 카페는 팬덤과 관심사 커뮤니티로 남았습니다. 포털 기능은 Kakao 생태계와 연결되며 지금도 운영되고 있습니다.') WHERE id='web-daum';
--> statement-breakpoint
UPDATE content_items SET body='Anycall SCH-800은 1998년 출시된 삼성전자의 초기 CDMA 폴더형 휴대전화입니다. 안테나와 덮개를 갖춘 작은 본체에 통화·문자 기능을 담아 바 타입 중심이던 시장에서 휴대성과 조형미를 강조했고, 애니콜이 국내 대표 휴대전화 브랜드로 성장하는 초석이 됐습니다.', metadata=json_set(metadata,'$.story.significance','국내 CDMA 시장에서 폴더 구조를 대중화하며 휴대전화가 성능뿐 아니라 손에 쥐고 여닫는 디자인으로 선택되는 제품임을 보여줬습니다.','$.story.legacy','애니콜의 폴더폰 계보는 컬러 화면·카메라·MP3·DMB를 결합한 피처폰으로 발전했고, 삼성 모바일 브랜드의 경험은 Galaxy 시리즈로 이어졌습니다.') WHERE id='phone-samsung-sch800';
--> statement-breakpoint
UPDATE content_items SET body='Google은 1998년 문을 연 웹 검색 서비스입니다. 링크 구조를 활용해 문서의 중요도를 판단하는 검색 방식과 검색창에 집중한 가벼운 첫 화면으로 방대한 웹에서 필요한 정보를 찾는 시간을 줄였고, 검색을 지도·메일·동영상·모바일 운영체제로 이어지는 플랫폼의 출발점으로 만들었습니다.', metadata=json_set(metadata,'$.story.significance','포털 메뉴보다 검색 의도에 집중한 화면과 관련도 중심 결과는 웹 탐색의 기준을 바꾸고 검색 광고라는 거대한 산업을 성장시켰습니다.','$.story.legacy','미니멀한 검색 경험은 지금도 Google의 중심에 남아 있으며, 검색은 YouTube·Maps·Android와 생성형 AI를 연결하는 정보 접근 계층으로 발전했습니다.') WHERE id='web-google';
--> statement-breakpoint
UPDATE content_items SET body='MSN Messenger는 Microsoft가 1999년 시작한 PC용 인스턴트 메신저입니다. 친구의 접속 여부, 대화명과 상태 메시지, 이모티콘·파일 전송을 한 창에 모아 전화나 이메일보다 가벼운 실시간 대화를 일상화했고 Windows Live Messenger로 이름을 바꾸며 2000년대 글로벌 메신저 문화를 대표했습니다.', metadata=json_set(metadata,'$.story.significance','로그인 알림과 상태 표현은 온라인에서 함께 있다는 감각을 만들었고, 메신저가 PC를 켜는 중요한 이유가 되는 시대를 열었습니다.','$.story.legacy','서비스는 2013년 Skype로 통합됐지만 상태 메시지·친구 목록·실시간 채팅의 문법은 모바일 메신저와 협업 도구에 그대로 남았습니다.') WHERE id='service-msn';
--> statement-breakpoint
UPDATE content_items SET body='NAVER는 1999년 시작한 한국어 검색 포털입니다. 여러 영역의 결과를 한 번에 보여주는 통합검색과 이용자가 질문하고 답하는 지식iN, 뉴스·카페·블로그를 결합해 한국어 웹 콘텐츠를 찾고 생산하는 대표 관문이 됐고 이후 지도·쇼핑·웹툰·클라우드로 영역을 넓혔습니다.', metadata=json_set(metadata,'$.story.significance','한국어 환경에 맞춘 통합검색과 지식iN은 흩어진 정보를 한 화면에서 발견하고 이용자가 직접 지식을 축적하는 국내 포털의 표준을 만들었습니다.','$.story.legacy','검색 중심의 첫 화면은 모바일 앱과 AI 검색으로 진화했고, 웹툰·쇼핑·지도 같은 버티컬 서비스는 국내외 독립 플랫폼으로 성장했습니다.') WHERE id='web-naver';
--> statement-breakpoint
UPDATE content_items SET summary='중국어 웹 검색을 중심으로 거대한 정보 플랫폼으로 성장한 검색 서비스', body='Baidu는 2000년 중국 베이징에서 시작한 중국어 중심 검색 엔진입니다. 중국어 형태와 현지 웹 환경에 맞춘 검색을 바탕으로 이미지·뉴스·지도·백과사전과 커뮤니티를 확장하며 중국 인터넷의 주요 관문이 됐고, 이후 모바일·클라우드·인공지능과 자율주행 기술로 사업을 넓혔습니다.', metadata=json_set(metadata,'$.story.significance','중국어 이용자가 현지 웹 문서와 서비스를 빠르게 찾을 수 있는 검색 기반을 만들며 중국 인터넷 산업의 독자적인 플랫폼 생태계를 형성했습니다.','$.story.legacy','검색과 광고 사업은 지금도 Baidu의 기반이며, 축적한 데이터와 AI 연구는 ERNIE 모델·클라우드·Apollo 자율주행 같은 후속 서비스로 발전했습니다.') WHERE id='milestone-2000-baidu';
--> statement-breakpoint
UPDATE content_items SET body='Nokia 3310은 2000년 출시된 GSM 바 타입 휴대전화입니다. 튼튼한 본체, 오래가는 배터리, 교체 가능한 Xpress-on 커버와 Snake II 게임을 결합해 전화기를 개인 취향을 드러내는 대중 제품으로 만들었고 세계적으로 널리 보급된 Nokia의 상징적인 모델이 됐습니다.', metadata=json_set(metadata,'$.story.significance','신뢰성·단순한 조작·개인화 커버를 균형 있게 제공해 휴대전화가 일부 전문가의 장비에서 누구나 쓰는 생활 필수품으로 이동하는 장면을 대표합니다.','$.story.legacy','원형은 단종됐지만 견고함의 상징으로 계속 회자되며, Nokia 브랜드는 2017년 같은 이름의 피처폰을 현대적으로 재해석해 기억을 계승했습니다.') WHERE id='phone-nokia-3310';
--> statement-breakpoint
UPDATE content_items SET body='Samsung SGH-T100은 2002년 세계 시장에 출시된 듀얼 스크린 폴더형 GSM 휴대전화입니다. 밝은 TFT 컬러 LCD와 작고 둥근 외형을 앞세워 흑백 화면에서 컬러 모바일 시대로의 전환을 보여줬고, 삼성 휴대전화 가운데 처음으로 누적 판매 천만 대를 넘긴 글로벌 히트 모델이 됐습니다.', metadata=json_set(metadata,'$.story.significance','컬러 화면을 대중적인 폴더폰에 적용하고 해외 시장에서 성공하며 삼성전자가 세계 휴대전화 제조사로 성장할 수 있다는 가능성을 증명했습니다.','$.story.legacy','T100의 컬러 디스플레이와 글로벌 유통 경험은 이후 카메라폰·Ultra Edition·Galaxy로 이어지는 삼성 모바일 제품군의 토대가 됐습니다.') WHERE id='phone-samsung-t100';
--> statement-breakpoint
UPDATE content_items SET body='NateOn은 SK커뮤니케이션즈가 2003년 선보인 PC용 인스턴트 메신저입니다. 무료 문자, 대용량 파일 전송, 원격제어와 싸이월드 연동처럼 국내 이용 환경에 맞춘 기능으로 학교와 직장까지 빠르게 퍼졌고 MSN Messenger를 넘어 한국 데스크톱 메신저의 중심에 올랐습니다.', metadata=json_set(metadata,'$.story.significance','통신사 문자와 커뮤니티 계정을 메신저에 연결해 한국 이용자가 실제로 필요로 하던 업무·생활 기능을 한곳에 모은 대표적인 로컬 서비스였습니다.','$.story.legacy','모바일 메신저가 대화를 가져간 뒤에도 파일 전송과 원격제어를 중심으로 서비스를 이어가며 기업 협업형 메신저의 성격을 강화했습니다.') WHERE id='service-nateon';
--> statement-breakpoint
UPDATE content_items SET body='Facebook은 2004년 대학생 네트워크로 시작해 실명 프로필, 친구 관계와 뉴스피드를 중심으로 성장한 소셜 네트워크 서비스입니다. 이용자가 올린 글·사진과 주변 사람의 활동을 끊임없이 갱신되는 한 화면에 모으며 웹의 중심을 문서에서 사람과 관계로 이동시켰습니다.', metadata=json_set(metadata,'$.story.significance','뉴스피드와 소셜 그래프를 대중화해 콘텐츠 발견, 온라인 광고, 브랜드와 이용자의 소통 방식을 세계적으로 바꾸었습니다.','$.story.legacy','서비스는 Meta의 핵심 플랫폼으로 남아 있고, 피드·좋아요·공유 구조는 Instagram을 비롯한 현대 소셜 미디어의 기본 문법으로 이어졌습니다.') WHERE id='service-facebook';
--> statement-breakpoint
UPDATE content_items SET body='Motorola RAZR V3는 2004년 공개된 초슬림 폴더형 휴대전화입니다. 항공기 등급 알루미늄 외장, 레이저 각인 금속 키패드와 13.9mm 두께의 날카로운 실루엣을 결합해 전자기기를 패션 액세서리로 보이게 했고 세계적으로 1억 대 이상 팔린 Motorola의 대표작이 됐습니다.', metadata=json_set(metadata,'$.story.significance','기능 경쟁이 치열하던 시장에서 소재·비례·여닫는 감각 자체를 구매 이유로 만들며 휴대전화 산업에 디자인 중심 플래그십의 가치를 각인했습니다.','$.story.legacy','원형의 얇은 폴더 디자인은 오랫동안 Motorola의 상징으로 남았고, 2019년부터 화면이 접히는 스마트폰 razr 시리즈로 재해석됐습니다.') WHERE id='phone-motorola-razr';
--> statement-breakpoint
UPDATE content_items SET body='SKY IM-6500은 2004년 팬택&큐리텔이 선보인 슬라이드형 피처폰입니다. 손가락으로 돌리는 휠 내비게이션과 정제된 외형, 감각적인 광고를 결합해 복잡한 메뉴를 빠르게 다루면서도 남들과 다른 기기를 원하는 젊은 이용자의 취향을 공략했습니다.', metadata=json_set(metadata,'$.story.significance','사양보다 조작 감각과 브랜드 이미지를 앞세워 국내 피처폰 시장에서 SKY를 프리미엄 디자인 브랜드로 각인한 대표 모델입니다.','$.story.legacy','휠 입력과 슬라이드 구조는 사라졌지만 SKY가 보여준 감성적 제품 기획은 이후 국내 제조사의 UX·컬러·광고 경쟁에 영향을 남겼습니다.') WHERE id='phone-sky-im-6500';
--> statement-breakpoint
UPDATE content_items SET body='YouTube는 2005년 베타로 공개된 온라인 동영상 업로드·공유 서비스입니다. 별도 스트리밍 서버나 복잡한 재생 프로그램 없이 영상을 올리고 링크로 퍼가며 채널을 구독할 수 있게 해 UCC 열풍을 만들었고, 누구나 방송 제작자와 시청자가 되는 글로벌 영상 플랫폼으로 성장했습니다.', metadata=json_set(metadata,'$.story.significance','영상 배포의 기술적 장벽을 크게 낮춰 개인 창작자, 바이럴 문화와 인터넷 동영상 광고라는 새로운 미디어 산업을 만들었습니다.','$.story.legacy','Google 인수 뒤 모바일·라이브·Shorts·구독 사업으로 확장됐으며, 크리에이터 경제와 음악·교육·뉴스 소비의 핵심 기반으로 남아 있습니다.') WHERE id='service-youtube';
--> statement-breakpoint
UPDATE content_items SET body='BlackBerry Pearl 8100은 2006년 Research In Motion이 출시한 소형 스마트폰입니다. 두 글자를 한 키에 배치한 SureType 키보드, 진주처럼 빛나는 트랙볼과 카메라·음악 기능을 결합해 업무용 이메일 기기였던 BlackBerry를 일반 소비자에게 가까운 멀티미디어 폰으로 넓혔습니다.', metadata=json_set(metadata,'$.story.significance','푸시 이메일이라는 BlackBerry의 강점을 유지하면서 크기와 디자인을 대중화해 스마트폰이 기업 밖의 일상용 제품으로 확장되는 전환을 보여줬습니다.','$.story.legacy','Pearl의 트랙볼과 압축 키보드는 사라졌지만 메시징·보안·생산성 중심 정체성은 Bold와 KEY 시리즈까지 이어졌습니다.') WHERE id='phone-blackberry-pearl';
--> statement-breakpoint
UPDATE content_items SET body='LG Chocolate KG800은 2006년 세계 시장에 출시된 슬라이드형 디자인폰입니다. 닫았을 때 버튼이 보이지 않는 검은 전면, 붉게 빛나는 터치 키와 초콜릿이라는 감성적 이름을 결합해 LG의 기술을 하나의 시각적 인상으로 압축했고 세계적인 판매 성공을 거뒀습니다.', metadata=json_set(metadata,'$.story.significance','휴대전화를 기능표가 아니라 컬러·소재·이름으로 기억하게 만들며 한국 제조사의 디자인 경쟁력을 세계 시장에 알린 대표 사례입니다.','$.story.legacy','Chocolate은 LG의 Black Label 시리즈와 Prada Phone 같은 디자인 실험으로 이어졌고, 매끈한 전면과 터치 입력은 풀터치 스마트폰 시대로 연결됐습니다.') WHERE id='phone-lg-chocolate';
--> statement-breakpoint
UPDATE content_items SET body='Anycall HAPTIC은 2008년 삼성전자가 선보인 풀터치 피처폰입니다. 손가락 조작에 반응하는 진동 피드백, 화면에 배치하는 위젯과 DMB를 결합해 물리 키패드 없이 휴대전화를 다루는 경험을 국내에 대중화했고 스마트폰 전환 직전의 터치 UI를 대표했습니다.', metadata=json_set(metadata,'$.story.significance','터치할 때 손끝으로 반응을 확인하게 하고 자주 쓰는 기능을 위젯으로 꺼내 놓아, 국내 이용자가 화면 중심 인터페이스에 익숙해지는 다리를 놓았습니다.','$.story.legacy','HAPTIC의 터치·위젯 경험과 대규모 마케팅은 이후 삼성의 Android 기반 Galaxy 스마트폰 UI와 앱 중심 사용 방식으로 이어졌습니다.') WHERE id='phone-anycall-haptic';
--> statement-breakpoint
UPDATE content_items SET body='BlackBerry Bold 9000은 2008년 출시된 프리미엄 QWERTY 스마트폰입니다. 넓고 정확한 물리 키보드, 트랙볼, 빠른 푸시 이메일과 가죽 질감의 후면을 결합해 이동 중 메시지와 문서 업무를 처리하는 전문가용 스마트폰의 이미지를 완성했습니다.', metadata=json_set(metadata,'$.story.significance','통신·보안·키보드 입력을 안정적으로 묶어 스마트폰이 엔터테인먼트 기기이기 전에 생산성 도구가 될 수 있음을 가장 분명하게 보여줬습니다.','$.story.legacy','Bold의 키보드와 보안 중심 정체성은 BlackBerry Classic과 KEY 시리즈로 이어졌고, 단축키와 알림 허브 개념은 현대 업무용 모바일 UX에 남았습니다.') WHERE id='phone-blackberry-bold';
--> statement-breakpoint
UPDATE content_items SET body='BlackBerry Torch 9800은 2010년 출시된 세로 슬라이드형 스마트폰입니다. 3.2인치 터치 화면 아래에 전통적인 QWERTY 키보드를 숨기고 BlackBerry OS 6의 웹 브라우저와 소셜 기능을 담아 기존 업무 사용성과 iPhone 이후의 터치 인터페이스를 동시에 수용하려 했습니다.', metadata=json_set(metadata,'$.story.significance','물리 키보드 이용자를 놓치지 않으면서 터치 중심 시장에 대응한 과도기적 설계로, 당시 BlackBerry가 마주한 플랫폼 전환의 고민을 선명하게 보여줍니다.','$.story.legacy','슬라이드 구조는 주류가 되지 못했지만 키보드와 터치를 함께 쓰려는 시도는 Priv로 이어졌고, 생산성 중심 Android 기기라는 후대 방향을 예고했습니다.') WHERE id='phone-blackberry-torch';
--> statement-breakpoint
UPDATE content_items SET body='Instagram은 2010년 iPhone 앱으로 시작한 모바일 사진 공유 서비스입니다. 스마트폰으로 찍은 사진을 정사각형으로 자르고 필터를 적용해 피드에 바로 올리는 과정을 하나로 묶어 평범한 일상을 시각적으로 기록하는 습관을 만들었고, 사진 중심 소셜 플랫폼으로 빠르게 성장했습니다.', metadata=json_set(metadata,'$.story.significance','촬영·보정·공유의 장벽을 낮추고 이미지 자체를 대화 수단으로 만들며 모바일 카메라와 인플루언서 문화의 성장을 가속했습니다.','$.story.legacy','Meta 인수 뒤 Stories·Reels·쇼핑으로 확장됐고, 세로 영상과 창작자 중심 추천 피드를 결합한 현재의 종합 비주얼 플랫폼으로 발전했습니다.') WHERE id='service-instagram';
--> statement-breakpoint
UPDATE content_items SET body='KakaoTalk은 2010년 출시된 전화번호 기반 모바일 메신저입니다. 데이터망을 이용한 무료 1대1·그룹 채팅과 간단한 친구 등록으로 SMS 비용과 길이의 제약을 없앴고, 이모티콘·보이스톡·선물하기를 더하며 한국인의 일상 소통과 생활 서비스를 한 앱에 연결했습니다.', metadata=json_set(metadata,'$.story.significance','스마트폰 보급 초기에 모바일 데이터 기반 대화를 빠르게 정착시켜 문자메시지 중심이던 통신 습관과 국내 모바일 플랫폼 경쟁을 근본적으로 바꿨습니다.','$.story.legacy','채팅은 Kakao 생태계의 출발점이 됐고 결제·택시·콘텐츠·업무 도구로 확장되며 오늘날에도 한국의 대표 생활 플랫폼 역할을 하고 있습니다.') WHERE id='service-kakaotalk';
--> statement-breakpoint
UPDATE content_items SET body='Samsung Galaxy S는 2010년 출시된 삼성전자의 첫 Galaxy S 플래그십 스마트폰입니다. 얇은 풀터치 본체에 4인치 Super AMOLED, Android와 삼성의 모바일 기술을 결합해 iPhone 중심이던 글로벌 시장에 본격적으로 진입했고 매년 이어지는 대표 스마트폰 제품군의 출발점이 됐습니다.', metadata=json_set(metadata,'$.story.significance','디스플레이·반도체·제조 역량을 하나의 Android 제품으로 묶어 삼성이 세계 스마트폰 시장의 핵심 경쟁자로 올라서는 기반을 만들었습니다.','$.story.legacy','Galaxy S는 대화면·카메라·S Pen·폴더블과 AI 기능을 흡수하며 계속 발전했고, 현재까지 삼성 모바일 플래그십의 중심 계보로 이어집니다.') WHERE id='phone-galaxy-s';
--> statement-breakpoint
UPDATE content_items SET body='LINE은 2011년 일본에서 시작한 모바일 메신저입니다. 전화번호 기반 채팅과 무료 음성 통화에 감정을 크게 표현하는 캐릭터 스티커를 결합해 재난 이후 안정적인 소통 도구로 성장했고 일본·대만·태국 등에서 생활 플랫폼으로 자리 잡았습니다.', metadata=json_set(metadata,'$.story.significance','문자 이모티콘을 큼직한 캐릭터 상품으로 발전시켜 메신저 대화의 시각 언어와 디지털 캐릭터 사업 모델을 크게 확장했습니다.','$.story.legacy','브라운·코니 같은 캐릭터는 콘텐츠와 상품으로 이어졌고, LINE은 결제·뉴스·게임·업무 기능을 통합한 LY Corporation의 핵심 서비스로 남아 있습니다.') WHERE id='service-line';
--> statement-breakpoint
UPDATE content_items SET body='LG Optimus G는 2012년 출시된 LG전자의 Android 플래그십 스마트폰입니다. 유리 아래에서 각도에 따라 무늬가 달라지는 크리스털 리플렉션 후면, Snapdragon S4 Pro와 True HD IPS+ 화면을 결합해 LG 계열사의 부품 역량을 집약했고 이후 G 시리즈의 기반이 됐습니다.', metadata=json_set(metadata,'$.story.significance','디스플레이·배터리·카메라와 화학 소재까지 그룹의 기술을 한 제품에 모아 LG 스마트폰이 성능과 디자인 모두에서 플래그십 경쟁에 나선 전환점이 됐습니다.','$.story.legacy','Optimus 명칭은 사라졌지만 설계 경험은 LG G2의 후면 버튼과 G 시리즈, Google Nexus 4 같은 협업 제품으로 이어졌습니다.') WHERE id='phone-lg-optimus-g';
--> statement-breakpoint
UPDATE content_items SET body='Samsung Galaxy S III는 2012년 출시된 Android 플래그십 스마트폰입니다. 4.8인치 HD Super AMOLED, 둥근 조약돌 형태와 시선을 감지하는 Smart Stay 같은 기능을 앞세워 대화면 스마트폰을 대중화했고 Galaxy 브랜드를 세계적인 주력 제품군으로 끌어올렸습니다.', metadata=json_set(metadata,'$.story.significance','큰 화면과 얇은 본체, 차별화된 소프트웨어 기능을 성공적으로 결합해 Android 진영의 대표 제품이자 iPhone의 강력한 경쟁자로 자리 잡았습니다.','$.story.legacy','대화면·멀티태스킹·AMOLED 중심의 방향은 이후 Galaxy S와 Note 시리즈에 통합됐고 오늘날 삼성 플래그십 UX의 기본으로 발전했습니다.') WHERE id='phone-galaxy-s3';
--> statement-breakpoint
UPDATE content_items SET summary='후면 버튼과 얇은 베젤로 한 손 조작의 방향을 새롭게 제안한 LG 플래그십', body='LG G2는 2013년 출시된 LG전자의 Android 플래그십 스마트폰입니다. 전원·음량 버튼을 후면 카메라 아래로 옮긴 Rear Key, 얇은 베젤의 5.2인치 화면과 KnockON을 적용해 큰 화면을 한 손으로 다루는 새로운 조작 방식을 제안했습니다.', metadata=json_set(metadata,'$.highlights',json_array('후면 Rear Key','5.2인치 얇은 베젤','KnockON'),'$.story.significance','스마트폰 옆면 버튼이라는 관습을 바꾸고 손가락이 자연스럽게 닿는 후면을 입력 공간으로 활용해 LG만의 뚜렷한 디자인 정체성을 만들었습니다.','$.story.legacy','후면 버튼은 G3·G4와 V 시리즈 일부로 이어졌고, KnockON 같은 화면 깨우기 제스처는 다양한 제조사의 스마트폰 UX에 널리 정착했습니다.') WHERE id='milestone-2013-lg-g2';
--> statement-breakpoint
UPDATE content_items SET body='Zoom은 2013년 정식 서비스를 시작한 클라우드 기반 화상회의 플랫폼입니다. 링크 하나로 회의에 참여하는 단순한 흐름, 안정적인 다자간 영상·화면 공유와 갤러리 보기를 제공했고 2020년 팬데믹을 계기로 학교·직장·가족을 연결하는 보편적인 원격 소통 도구가 됐습니다.', metadata=json_set(metadata,'$.story.significance','설치와 회의실 장비의 부담을 낮춰 화상회의를 전문 기업용 시스템에서 누구나 사용할 수 있는 일상적 서비스로 바꾸었습니다.','$.story.legacy','팬데믹 이후에도 하이브리드 업무와 수업의 기반으로 남았고, 채팅·전화·문서와 AI 회의 요약을 결합한 협업 플랫폼으로 확장되고 있습니다.') WHERE id='service-zoom';
--> statement-breakpoint
UPDATE content_items SET summary='QHD 화면과 레이저 자동초점으로 고해상도 스마트폰 경쟁을 이끈 LG 플래그십', body='LG G3는 2014년 출시된 LG전자의 Android 플래그십 스마트폰입니다. 5.5인치 QHD 디스플레이, 레이저 자동초점 카메라와 G2에서 이어진 후면 버튼을 곡면 본체에 담아 큰 고해상도 화면과 빠른 촬영을 핵심 경험으로 내세웠습니다.', metadata=json_set(metadata,'$.highlights',json_array('5.5인치 QHD 화면','레이저 자동초점','후면 버튼'),'$.story.significance','스마트폰에 QHD 해상도와 레이저 거리 측정을 선제적으로 적용해 화면·카메라 사양 경쟁의 새로운 기준을 제시했습니다.','$.story.legacy','G3의 고해상도 화면과 카메라 중심 전략은 G4·V 시리즈로 이어졌고, 빠른 자동초점은 이후 스마트폰 카메라의 핵심 경쟁 요소가 됐습니다.') WHERE id='milestone-2014-lg-g3';
--> statement-breakpoint
UPDATE content_items SET summary='가죽 후면과 밝은 조리개 카메라로 소재와 촬영 감성을 강조한 LG 플래그십', body='LG G4는 2015년 출시된 LG전자의 Android 플래그십 스마트폰입니다. 손으로 가공한 천연가죽 후면 선택지, 완만하게 휜 본체와 F1.8 조리개 카메라·전문가 모드를 결합해 화면 사양뿐 아니라 손에 닿는 소재와 촬영 경험을 차별점으로 삼았습니다.', metadata=json_set(metadata,'$.highlights',json_array('천연가죽 후면','F1.8 카메라','전문가 촬영 모드'),'$.story.significance','금속과 유리가 주류가 되던 시기에 가죽 소재와 수동 카메라 제어를 내세워 플래그십 디자인과 모바일 사진의 다른 가능성을 보여줬습니다.','$.story.legacy','가죽 실험은 짧게 끝났지만 전문가 촬영 UI와 광각·고음질 같은 차별화 전략은 이후 LG V 시리즈의 멀티미디어 정체성으로 발전했습니다.') WHERE id='milestone-2015-lg-g4';
--> statement-breakpoint
UPDATE content_items SET body='Motorola Moto X Style은 2015년 발표된 대화면 Android 스마트폰입니다. 5.7인치 QHD 화면, 전면 스테레오 스피커와 비교적 순정에 가까운 Android에 Moto Maker의 색상·소재 선택을 더해 제조사 기능을 과도하게 얹지 않으면서 사용자가 외형을 고르는 경험을 강조했습니다.', metadata=json_set(metadata,'$.story.significance','플래그십 성능과 깨끗한 소프트웨어, 주문형 외관 개인화를 결합해 스마트폰 차별화가 기능 추가만이 아니라 선택권과 사용 감각에서도 가능함을 보여줬습니다.','$.story.legacy','Moto Maker는 종료됐지만 가벼운 Android와 Moto Display·제스처 같은 접근은 이후 Motorola Edge와 Moto G 제품군의 소프트웨어 철학으로 이어졌습니다.') WHERE id='phone-moto-x-style';
--> statement-breakpoint
UPDATE content_items SET body='Samsung Galaxy S6는 2015년 출시된 Android 플래그십 스마트폰입니다. 플라스틱과 교체형 배터리를 벗어나 금속 프레임·유리 후면, 빠르게 실행되는 카메라와 무선 충전을 채택했고 Edge 모델에는 양쪽으로 휜 화면을 적용해 Galaxy의 소재와 디자인 방향을 크게 바꿨습니다.', metadata=json_set(metadata,'$.story.significance','제조 완성도와 카메라 경험을 전면에 내세우며 Galaxy가 사양 중심 제품에서 정교한 산업 디자인의 프리미엄 브랜드로 이동하는 전환점이 됐습니다.','$.story.legacy','메탈·글라스 일체형 구조와 곡면 디스플레이는 이후 Galaxy S 시리즈의 기본 언어가 됐고, 빠른 카메라 실행과 무선 충전도 표준 기능으로 자리 잡았습니다.') WHERE id='phone-galaxy-s6';
--> statement-breakpoint
UPDATE content_items SET body='TikTok은 2017년 국제 시장에 출시되고 musical.ly와 통합되며 성장한 세로형 숏폼 동영상 서비스입니다. 음악에 맞춘 짧은 촬영·편집 도구와 팔로우 관계보다 시청 반응을 앞세운 For You 추천 피드를 결합해 누구나 빠르게 만들고 발견되는 영상 문화를 세계적으로 확산했습니다.', metadata=json_set(metadata,'$.story.significance','세로 전체화면·짧은 재생·강한 개인화 추천을 하나의 연속 경험으로 묶어 모바일 영상의 길이, 유행의 속도와 콘텐츠 발견 방식을 바꾸었습니다.','$.story.legacy','숏폼 문법은 Instagram Reels와 YouTube Shorts로 확산됐고, TikTok은 음악·검색·쇼핑과 창작자 생태계를 결합한 문화 플랫폼으로 발전하고 있습니다.') WHERE id='service-tiktok';
--> statement-breakpoint
UPDATE content_items SET body='BlackBerry KEY2는 2018년 TCL Communication이 BlackBerry 브랜드로 출시한 Android 스마트폰입니다. 화면 아래 4열 물리 QWERTY 키보드, 앱을 바로 여는 Speed Key와 DTEK 보안 관리 기능을 결합해 터치폰 시대에도 정확한 타이핑과 업무 단축키를 원하는 이용자를 겨냥했습니다.', metadata=json_set(metadata,'$.story.significance','전면 화면이 표준이 된 시장에서 BlackBerry의 키보드·보안 정체성을 현대 Android 앱 생태계와 결합한 마지막 본격 계승 모델이라는 의미가 있습니다.','$.story.legacy','KEY2 이후 TCL의 BlackBerry 기기 생산은 종료됐지만 물리 키보드를 선호하는 수요와 단축 입력의 가치는 특수 목적 스마트폰과 액세서리에서 이어지고 있습니다.') WHERE id='phone-blackberry-key2';
--> statement-breakpoint
UPDATE content_items SET body='Samsung Galaxy S9은 2018년 출시된 Android 플래그십 스마트폰입니다. 주변 밝기에 따라 F1.5와 F2.4를 바꾸는 듀얼 조리개, 초고속 촬영과 스테레오 스피커를 인피니티 디스플레이 본체에 담아 외형을 급격히 바꾸기보다 카메라와 미디어 경험을 정교하게 다듬었습니다.', metadata=json_set(metadata,'$.story.significance','스마트폰 카메라에 가변 조리개를 적용해 어두운 환경의 촬영 품질을 하드웨어로 해결하려 했고, 성숙한 플래그십의 완성도 경쟁을 대표했습니다.','$.story.legacy','가변 조리개는 후속 주류 기능으로 남지 않았지만 저조도 촬영과 고속 영상 경쟁은 멀티 카메라·컴퓨테이셔널 포토그래피로 발전했습니다.') WHERE id='phone-galaxy-s9';
--> statement-breakpoint
UPDATE content_items SET body='LG WING은 2020년 출시된 5G Android 스마트폰입니다. 위쪽 6.8인치 화면을 90도로 돌리면 아래 보조 화면이 드러나는 스위블 구조를 사용해 영상을 보며 댓글·지도·촬영 제어를 동시에 다루고, 짐벌 모션 카메라로 새로운 멀티태스킹 형태를 실험했습니다.', metadata=json_set(metadata,'$.story.significance','모든 스마트폰이 같은 직사각형 판으로 수렴하던 시기에 회전 메커니즘과 듀얼 화면을 결합해 앱을 동시에 사용하는 물리적 인터페이스를 제안했습니다.','$.story.legacy','LG의 휴대전화 사업 종료로 후속작은 나오지 않았지만 WING은 폴더블·롤러블과 함께 스마트폰 폼팩터 실험의 독특한 사례로 남았습니다.') WHERE id='phone-lg-wing';
--> statement-breakpoint
UPDATE content_items SET body='Samsung Galaxy S20은 2020년 출시된 5G Android 플래그십 스마트폰 시리즈입니다. 120Hz AMOLED 화면, 고화소 센서와 Space Zoom, 8K 동영상 촬영을 결합해 빠른 화면과 원거리 촬영, 차세대 이동통신을 한 세대의 핵심 사양으로 제시했습니다.', metadata=json_set(metadata,'$.story.significance','5G와 고주사율을 주력 Galaxy 전 모델의 전면에 내세우고 카메라 센서·배율 경쟁을 가속하며 2020년대 플래그십의 성능 기준을 정리했습니다.','$.story.legacy','S20의 고주사율·대형 센서·5G 방향은 후속 Galaxy S 시리즈의 기본이 됐고, Ultra 모델은 최고 사양과 S Pen 계보를 흡수하는 상위 축으로 발전했습니다.') WHERE id='phone-galaxy-s20';
--> statement-breakpoint
UPDATE content_items SET summary='멀티터치 화면과 손가락 중심 UI로 스마트폰의 기준을 다시 세운 첫 iPhone', body='iPhone은 Apple이 2007년 출시한 첫 스마트폰입니다. 3.5인치 정전식 멀티터치 화면에 전화, iPod과 Safari 기반 인터넷 기능을 하나로 묶고 물리 키패드 대신 손가락 제스처로 화면을 직접 다루게 해 모바일 컴퓨팅의 중심을 하드웨어 버튼에서 소프트웨어로 옮겼습니다.', metadata=json_set(metadata,'$.highlights',json_array('정전식 멀티터치','Mobile Safari','전화·iPod·인터넷 통합'),'$.story.significance','핀치 투 줌과 관성 스크롤 같은 직접 조작을 대중화하고 웹 브라우징을 휴대전화의 핵심 경험으로 만들며 스마트폰 산업의 설계 기준을 바꿨습니다.','$.story.legacy','이듬해 App Store가 더해지며 앱 생태계가 형성됐고, 홈 버튼 없는 전면 화면·생체 인증·고성능 모바일 칩으로 발전한 현재 iPhone 계보의 출발점이 됐습니다.'), content_version=content_version+1, updated_at=unixepoch()*1000 WHERE id='milestone-2007-iphone';
--> statement-breakpoint
UPDATE media SET source_url='/images/archive/milestones/2007-iphone.webp', updated_at=unixepoch()*1000 WHERE id IN (SELECT media_id FROM content_media WHERE content_id='milestone-2007-iphone' AND role='hero') AND trim(source_url)='';
--> statement-breakpoint
UPDATE content_items
SET quality_status='verified', verified_at=unixepoch()*1000, content_version=content_version+1, updated_at=unixepoch()*1000
WHERE id IN ('web-daum','phone-samsung-sch800','web-google','service-msn','web-naver','milestone-2000-baidu','phone-nokia-3310','phone-samsung-t100','service-nateon','service-facebook','phone-motorola-razr','phone-sky-im-6500','service-youtube','phone-blackberry-pearl','phone-lg-chocolate','phone-anycall-haptic','phone-blackberry-bold','phone-blackberry-torch','service-instagram','service-kakaotalk','phone-galaxy-s','service-line','phone-lg-optimus-g','phone-galaxy-s3','milestone-2013-lg-g2','service-zoom','milestone-2014-lg-g3','milestone-2015-lg-g4','phone-moto-x-style','phone-galaxy-s6','service-tiktok','phone-blackberry-key2','phone-galaxy-s9','phone-lg-wing','phone-galaxy-s20');
--> statement-breakpoint
INSERT INTO content_review_events (id,content_id,actor_id,action,from_status,to_status,note,created_at)
SELECT 'v043-verified-' || id,id,NULL,'verified','needs_review','verified','v0.4.3 개별 설명·의의·계보 편집 검수 완료',unixepoch()*1000 FROM content_items
WHERE id IN ('web-daum','phone-samsung-sch800','web-google','service-msn','web-naver','milestone-2000-baidu','phone-nokia-3310','phone-samsung-t100','service-nateon','service-facebook','phone-motorola-razr','phone-sky-im-6500','service-youtube','phone-blackberry-pearl','phone-lg-chocolate','phone-anycall-haptic','phone-blackberry-bold','phone-blackberry-torch','service-instagram','service-kakaotalk','phone-galaxy-s','service-line','phone-lg-optimus-g','phone-galaxy-s3','milestone-2013-lg-g2','service-zoom','milestone-2014-lg-g3','milestone-2015-lg-g4','phone-moto-x-style','phone-galaxy-s6','service-tiktok','phone-blackberry-key2','phone-galaxy-s9','phone-lg-wing','phone-galaxy-s20');
--> statement-breakpoint
PRAGMA optimize;
