import { index, integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const audit = {
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
};

export const brands = sqliteTable("brands", { id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(), description: text("description").notNull().default(""), ...audit }, (t) => [uniqueIndex("uq_brands_slug").on(t.slug)]);
export const eras = sqliteTable("eras", { id: text("id").primaryKey(), year: integer("year").notNull(), title: text("title").notNull(), summary: text("summary").notNull().default(""), status: text("status", { enum: ["draft", "published"] }).notNull().default("draft"), ...audit }, (t) => [uniqueIndex("uq_eras_year").on(t.year)]);
export const categories = sqliteTable("categories", { id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(), description: text("description").notNull().default(""), ...audit }, (t) => [uniqueIndex("uq_categories_slug").on(t.slug)]);

export const contentItems = sqliteTable("content_items", {
  id: text("id").primaryKey(), type: text("type", { enum: ["website", "phone", "product", "service", "event", "game", "program"] }).notNull(),
  slug: text("slug").notNull(), name: text("name").notNull(), summary: text("summary").notNull().default(""), body: text("body").notNull().default(""),
  startYear: integer("start_year").notNull(), endYear: integer("end_year"), brandId: text("brand_id").references(() => brands.id, { onDelete: "set null" }), categoryId: text("category_id").references(() => categories.id, { onDelete: "set null" }),
  accent: text("accent").notNull().default("#9bcbe2"), status: text("status", { enum: ["draft", "review", "published", "archived"] }).notNull().default("draft"), featured: integer("featured", { mode: "boolean" }).notNull().default(false), metadata: text("metadata", { mode: "json" }).$type<Record<string, unknown>>().notNull().default({}), publishedAt: integer("published_at", { mode: "timestamp_ms" }), ...audit,
}, (t) => [uniqueIndex("uq_content_type_slug").on(t.type, t.slug), index("idx_content_year_status").on(t.startYear, t.status), index("idx_content_brand_id").on(t.brandId)]);

export const media = sqliteTable("media", { id: text("id").primaryKey(), objectKey: text("object_key").notNull(), filename: text("filename").notNull(), mimeType: text("mime_type").notNull(), byteSize: integer("byte_size").notNull(), width: integer("width"), height: integer("height"), altText: text("alt_text").notNull().default(""), credit: text("credit"), sourceUrl: text("source_url"), ...audit }, (t) => [uniqueIndex("uq_media_object_key").on(t.objectKey)]);
export const galleries = sqliteTable("galleries", { id: text("id").primaryKey(), contentId: text("content_id").notNull().references(() => contentItems.id, { onDelete: "cascade" }), title: text("title").notNull(), sortOrder: integer("sort_order").notNull().default(0), ...audit }, (t) => [index("idx_galleries_content_id").on(t.contentId)]);
export const galleryMedia = sqliteTable("gallery_media", { galleryId: text("gallery_id").notNull().references(() => galleries.id, { onDelete: "cascade" }), mediaId: text("media_id").notNull().references(() => media.id, { onDelete: "cascade" }), sortOrder: integer("sort_order").notNull().default(0), caption: text("caption") }, (t) => [primaryKey({ columns: [t.galleryId, t.mediaId] })]);
export const websiteSnapshots = sqliteTable("website_snapshots", { id: text("id").primaryKey(), contentId: text("content_id").notNull().references(() => contentItems.id, { onDelete: "cascade" }), year: integer("year").notNull(), title: text("title").notNull(), description: text("description").notNull().default(""), sourceUrl: text("source_url"), mediaId: text("media_id").references(() => media.id, { onDelete: "set null" }), ...audit }, (t) => [uniqueIndex("uq_snapshot_content_year").on(t.contentId, t.year)]);
export const phoneProfiles = sqliteTable("phone_profiles", { contentId: text("content_id").primaryKey().references(() => contentItems.id, { onDelete: "cascade" }), releasePrice: integer("release_price"), carrier: text("carrier"), colors: text("colors", { mode: "json" }).$type<string[]>().notNull().default([]), specifications: text("specifications", { mode: "json" }).$type<Record<string, string>>().notNull().default({}), ...audit });
export const tags = sqliteTable("tags", { id: text("id").primaryKey(), slug: text("slug").notNull(), name: text("name").notNull(), ...audit }, (t) => [uniqueIndex("uq_tags_slug").on(t.slug)]);
export const contentTags = sqliteTable("content_tags", { contentId: text("content_id").notNull().references(() => contentItems.id, { onDelete: "cascade" }), tagId: text("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }) }, (t) => [primaryKey({ columns: [t.contentId, t.tagId] })]);
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email"), displayName: text("display_name").notNull(), role: text("role", { enum: ["member", "editor", "admin"] }).notNull().default("member"), ...audit }, (t) => [uniqueIndex("uq_users_email").on(t.email)]);
export const collections = sqliteTable("collections", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }), deviceKey: text("device_key"), name: text("name").notNull().default("내 추억 컬렉션"), isPublic: integer("is_public", { mode: "boolean" }).notNull().default(false), ...audit }, (t) => [index("idx_collections_user_id").on(t.userId)]);
export const collectionItems = sqliteTable("collection_items", { collectionId: text("collection_id").notNull().references(() => collections.id, { onDelete: "cascade" }), contentId: text("content_id").notNull().references(() => contentItems.id, { onDelete: "cascade" }), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()) }, (t) => [primaryKey({ columns: [t.collectionId, t.contentId] })]);
export const memories = sqliteTable("memories", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "set null" }), contentId: text("content_id").notNull().references(() => contentItems.id, { onDelete: "cascade" }), body: text("body").notNull(), status: text("status", { enum: ["pending", "published", "hidden"] }).notNull().default("pending"), ...audit }, (t) => [index("idx_memories_content_status").on(t.contentId, t.status)]);
