import type { CatalogItem } from "./types";
import gameImages from "./game-images.json";

type GameSeed = {
  year: number;
  name: string;
  studio: string;
  genre: string;
  platform: string;
  milestone: string;
  eyebrow: string;
  summary: string;
  description: string;
  significance: string;
  legacy: string;
  highlights: string[];
  source: { label: string; url: string };
  accent: string;
};

const games: GameSeed[] = [
  { year: 1998, name: "StarCraft", studio: "Blizzard Entertainment", genre: "실시간 전략", platform: "Windows, Mac OS", milestone: "정식 출시", eyebrow: "PC방과 e스포츠의 원형", summary: "세 종족의 비대칭 전략과 Battle.net 대전을 세계적인 경쟁 문화로 만든 RTS", description: "StarCraft는 테란·저그·프로토스가 서로 다른 방식으로 싸우는 실시간 전략 게임입니다. 빠른 네트워크 대전과 관전하기 좋은 경기 구조가 한국의 PC방 문화와 프로 리그 성장에 맞물리며 게임이 스포츠가 될 수 있음을 보여줬습니다.", significance: "정교한 종족 균형과 Battle.net을 통해 온라인 대전의 표준을 세웠고, 개인 플레이를 방송·리그·팬덤이 결합된 대중문화로 확장했습니다.", legacy: "빌드 오더, 리플레이 분석, 프로게이머와 리그 운영 방식은 후속 RTS뿐 아니라 오늘날의 e스포츠 전반에 남아 있습니다.", highlights: ["세 종족의 비대칭 밸런스", "Battle.net 온라인 대전", "글로벌 e스포츠의 출발점"], source: { label: "Blizzard 20주년 기록", url: "https://news.blizzard.com/en-gb/article/21656008/sc20-anniversary-stream" }, accent: "#263c67" },
  { year: 1999, name: "EverQuest", studio: "Sony Online Entertainment", genre: "MMORPG", platform: "Windows", milestone: "정식 출시", eyebrow: "3D 세계에 모인 수천 명", summary: "광대한 3D 세계와 협동 중심 플레이로 MMORPG의 가능성을 세계에 증명한 작품", description: "EverQuest는 수천 명의 플레이어가 하나의 3D 판타지 세계를 공유하며 모험하는 MMORPG입니다. 파티, 길드, 공격대처럼 다른 사람과 협력해야만 완성되는 구조를 앞세워 온라인 게임을 장기적인 사회적 공간으로 바꿨습니다.", significance: "대규모 3D 온라인 세계가 상업적으로 성공할 수 있음을 보여주며 이후 MMORPG의 퀘스트, 길드, 레이드 설계에 기준을 만들었습니다.", legacy: "월드 오브 워크래프트를 비롯한 현대 MMORPG의 사회 구조와 장기 운영 방식에서 EverQuest의 흔적을 찾을 수 있습니다.", highlights: ["대규모 3D 온라인 세계", "길드와 레이드 문화", "MMORPG 상업화의 분기점"], source: { label: "EverQuest 공식 15주년 기록", url: "https://www.everquest.com/news/15th-anniversary-article" }, accent: "#7d6644" },
  { year: 2000, name: "Diablo II", studio: "Blizzard North", genre: "액션 RPG", platform: "Windows, Mac OS", milestone: "정식 출시", eyebrow: "반복 플레이가 만든 중독성", summary: "무작위 아이템과 빠른 전투, 온라인 협동으로 액션 RPG의 문법을 완성한 작품", description: "Diablo II는 무작위로 생성되는 장비를 모으고 캐릭터의 기술 조합을 완성해 가는 액션 RPG입니다. Battle.net 협동과 거래, 시즌형 반복 플레이를 통해 한 번 끝내는 모험을 오랫동안 파고드는 취미로 바꿨습니다.", significance: "아이템 등급, 스킬 트리, 난이도 순환과 파밍이라는 구조를 대중화해 수많은 액션 RPG와 온라인 서비스 게임의 설계에 영향을 줬습니다.", legacy: "오늘날의 루트 중심 RPG, 시즌제 핵앤슬래시, 장비 빌드 커뮤니티는 Diablo II가 정립한 플레이 흐름을 발전시키고 있습니다.", highlights: ["무작위 전리품과 파밍", "Battle.net 협동·거래", "액션 RPG 장르의 기준"], source: { label: "Blizzard Diablo II 20주년 기록", url: "https://worldofwarcraft.blizzard.com/en-gb/news/23459856" }, accent: "#7d261f" },
  { year: 2001, name: "RuneScape", studio: "Jagex", genre: "MMORPG", platform: "웹 브라우저", milestone: "공개 베타", eyebrow: "브라우저에서 열린 모험", summary: "설치 부담을 낮춘 웹 기반 세계와 자유로운 성장으로 장수 MMORPG가 된 게임", description: "RuneScape는 브라우저에서 곧바로 접속해 전투, 제작, 채집, 거래를 자유롭게 즐기는 MMORPG입니다. 2001년 공개 베타는 저사양 PC에서도 거대한 온라인 세계를 경험하게 하며 접근성 중심의 운영 모델을 보여줬습니다.", significance: "무료 진입과 가벼운 클라이언트, 지속적인 콘텐츠 추가를 결합해 온라인 게임이 긴 시간에 걸쳐 이용자와 함께 성장하는 방식을 증명했습니다.", legacy: "현재의 RuneScape와 Old School RuneScape는 이용자 투표와 장기 업데이트를 통해 원형을 서로 다른 방식으로 이어가고 있습니다.", highlights: ["2001년 공개 베타", "브라우저 기반 MMORPG", "이용자와 함께하는 장기 운영"], source: { label: "Jagex 공식 회사 연혁", url: "https://www.jagex.com/who-we-are" }, accent: "#88723d" },
  { year: 2002, name: "Battlefield 1942", studio: "DICE", genre: "멀티플레이 FPS", platform: "Windows, Mac OS", milestone: "정식 출시", eyebrow: "64명이 만든 전장", summary: "보병·전차·항공기를 한 전장에 묶어 대규모 팀 기반 FPS를 대중화한 작품", description: "Battlefield 1942는 넓은 지도에서 보병과 각종 탑승 장비가 동시에 싸우는 팀 기반 FPS입니다. 개인의 사격 실력뿐 아니라 거점 점령과 병과 조합을 강조해 온라인 슈팅을 거대한 전장 체험으로 확장했습니다.", significance: "64인 전투, 탈것, 병과 역할과 점령전의 결합은 이후 Battlefield 시리즈와 대규모 멀티플레이 슈팅의 핵심 문법이 됐습니다.", legacy: "현대의 대규모 FPS가 사용하는 분대, 거점, 육해공 복합 전투 설계는 이 작품에서 시작된 흐름을 고도화한 것입니다.", highlights: ["최대 64인 온라인 전투", "보병과 탈것의 결합", "대규모 팀 FPS의 원형"], source: { label: "EA 10주년 기록", url: "https://www.ea.com/news/get-battlefield-1942-free-from-origin" }, accent: "#68756c" },
  { year: 2003, name: "MapleStory", studio: "Wizet · Nexon", genre: "2D MMORPG", platform: "Windows", milestone: "한국 공개 서비스", eyebrow: "횡스크롤 세계의 커뮤니티", summary: "친근한 2D 그래픽과 무료 서비스로 세계적인 온라인 커뮤니티가 된 MMORPG", description: "MapleStory는 횡스크롤 액션과 캐릭터 성장, 꾸미기와 커뮤니티를 결합한 2D MMORPG입니다. 낮은 진입 장벽과 밝은 시각 언어, 무료 플레이 모델을 바탕으로 여러 지역에 진출해 거대한 글로벌 이용자층을 만들었습니다.", significance: "부분 유료화와 아바타 꾸미기, 계절 이벤트가 결합된 장기 서비스 모델을 대중화하며 온라인 게임의 사업 구조와 팬 문화를 바꿨습니다.", legacy: "PC 원작은 계속 운영되고 있으며 모바일 버전, 굿즈, 음악회 등 게임 밖의 문화로도 확장된 장수 프랜차이즈가 됐습니다.", highlights: ["2D 횡스크롤 MMORPG", "글로벌 1억 명대 계정", "아바타와 부분 유료화 문화"], source: { label: "Nexon 공식 제품 연혁", url: "https://www.nexon.co.jp/en/products/" }, accent: "#e8984a" },
  { year: 2004, name: "World of Warcraft", studio: "Blizzard Entertainment", genre: "MMORPG", platform: "Windows, Mac OS", milestone: "오픈 베타·정식 출시", eyebrow: "MMORPG가 대중문화가 되다", summary: "거대한 세계와 친절한 퀘스트, 공격대 콘텐츠로 MMORPG의 대중화를 이끈 작품", description: "World of Warcraft는 Warcraft 세계를 누구나 탐험할 수 있는 온라인 공간으로 확장한 MMORPG입니다. 접근하기 쉬운 퀘스트와 명확한 역할 분담, 길드와 공격대 콘텐츠를 결합해 장르의 이용자 규모를 세계적으로 넓혔습니다.", significance: "대규모 온라인 게임도 친절한 동선과 안정적인 운영으로 대중적인 여가가 될 수 있음을 보여주며 구독형 서비스의 정점을 만들었습니다.", legacy: "확장팩과 클래식 서버가 함께 운영되며, 시즌과 공격대 중심의 현대 MMORPG 설계에 여전히 큰 기준점으로 남아 있습니다.", highlights: ["2004년 북미 오픈 베타", "길드와 공격대 콘텐츠", "MMORPG의 세계적 대중화"], source: { label: "Blizzard 20주년 기록", url: "https://worldofwarcraft.blizzard.com/en-us/news/24162447/wow-weekly-wrap-up-wow-classic-20th-anniversary-edition-and-more" }, accent: "#7c5b2c" },
  { year: 2005, name: "Guild Wars", studio: "ArenaNet", genre: "온라인 RPG", platform: "Windows", milestone: "정식 출시", eyebrow: "구독료 없는 온라인 RPG", summary: "인스턴스 모험과 경쟁전, 구독료 없는 운영으로 다른 MMORPG의 길을 제시한 작품", description: "Guild Wars는 도시에서 사람을 만나고 전투 지역은 파티 단위로 분리하는 온라인 RPG입니다. 월 구독료 없이 패키지와 확장팩으로 운영하면서 정교한 스킬 조합과 경쟁전을 강조해 독자적인 팬층을 만들었습니다.", significance: "서버 부담을 낮춘 인스턴스 구조와 공정한 PvP, 구독료 없는 모델은 온라인 RPG가 거대한 단일 세계만을 따를 필요가 없음을 보여줬습니다.", legacy: "Guild Wars 2의 이벤트 중심 세계와 수평적 성장 철학으로 이어졌고, 원작 또한 오랜 기간 공식 서버를 유지하고 있습니다.", highlights: ["월 구독료 없는 운영", "인스턴스 기반 모험", "스킬 조합 중심 PvP"], source: { label: "Guild Wars 공식 기념 페이지", url: "https://www.guildwars.com/en/events/anniversary" }, accent: "#9c3d32" },
  { year: 2006, name: "Roblox", studio: "Roblox Corporation", genre: "게임 제작 플랫폼", platform: "Windows", milestone: "공개 베타 출시", eyebrow: "플레이어가 만드는 세계", summary: "이용자가 직접 게임을 만들고 공유하는 구조로 거대한 창작 생태계를 만든 플랫폼", description: "Roblox는 하나의 완성된 게임보다 이용자가 직접 경험을 제작하고 다른 사람과 공유하는 플랫폼에 가깝습니다. 간단한 제작 도구와 아바타, 사회적 연결을 결합해 어린 창작자도 개발자와 운영자가 될 수 있는 공간을 만들었습니다.", significance: "사용자 제작 콘텐츠를 플랫폼의 중심에 두고 제작, 배포, 수익화를 하나의 생태계로 연결해 게임과 소셜 공간의 경계를 흐렸습니다.", legacy: "오늘날 Roblox는 콘솔과 모바일, VR까지 확장됐으며 브랜드 행사와 공연, 교육 콘텐츠가 함께 존재하는 대규모 창작 플랫폼으로 발전했습니다.", highlights: ["2006년 공개 베타", "사용자 제작 게임", "창작자 경제와 소셜 플랫폼"], source: { label: "Roblox 회사 정보", url: "https://en.help.roblox.com/hc/en-us/articles/203313370-Roblox-Company-Information" }, accent: "#d44848" },
  { year: 2007, name: "Team Fortress 2", studio: "Valve", genre: "팀 기반 FPS", platform: "Windows, Xbox 360, PlayStation 3", milestone: "베타·정식 출시", eyebrow: "역할과 개성이 만난 FPS", summary: "뚜렷한 아홉 병과와 애니메이션풍 미술로 팀 기반 슈팅의 대중성을 넓힌 작품", description: "Team Fortress 2는 공격, 방어, 지원 역할이 선명한 아홉 병과가 협력하는 멀티플레이 FPS입니다. 실루엣만으로도 역할을 알아볼 수 있는 캐릭터 디자인과 유머, 지속적인 무료 업데이트로 오랫동안 커뮤니티를 유지했습니다.", significance: "병과의 기능과 캐릭터성을 동시에 설계해 오늘날 히어로 슈터의 토대를 만들었고, 아이템과 커뮤니티 콘텐츠 중심 운영도 널리 확산시켰습니다.", legacy: "오버워치와 여러 팀 기반 슈터에서 역할 조합과 읽기 쉬운 캐릭터 디자인이라는 유산이 이어지고 있습니다.", highlights: ["2007년 Steam 베타", "아홉 개의 개성적인 병과", "히어로 슈터의 토대"], source: { label: "Steam 공식 제품 페이지", url: "https://store.steampowered.com/app/440/" }, accent: "#b2633f" },
  { year: 2008, name: "Left 4 Dead", studio: "Valve · Turtle Rock Studios", genre: "협동 FPS", platform: "Windows, Xbox 360", milestone: "데모·정식 출시", eyebrow: "네 명이 만드는 생존 이야기", summary: "AI가 매번 다른 위기를 연출하는 4인 협동 구조로 협동 슈팅의 기준을 세운 작품", description: "Left 4 Dead는 네 명의 생존자가 감염자 무리를 뚫고 탈출하는 협동 FPS입니다. 플레이 상황에 맞춰 적과 아이템, 긴장도를 조절하는 AI Director를 사용해 같은 지도를 반복해도 다른 이야기가 생기도록 만들었습니다.", significance: "개인의 점수보다 동료 구조와 속도 조절을 강조해 온라인 협동 플레이의 감정적 긴장과 반복성을 크게 끌어올렸습니다.", legacy: "4인 파티, 특수 적, 동적 난이도를 결합한 구조는 수많은 협동 액션 게임이 따르는 기본 형식으로 남았습니다.", highlights: ["4인 온라인 협동", "AI Director", "협동 슈팅 장르의 기준"], source: { label: "Left 4 Dead 공식 출시 기록", url: "https://www.l4d.com/blog/?p=52" }, accent: "#49644a" },
  { year: 2009, name: "League of Legends", studio: "Riot Games", genre: "MOBA", platform: "Windows, Mac OS", milestone: "오픈 베타·정식 출시", eyebrow: "무료 MOBA와 글로벌 리그", summary: "무료 플레이와 꾸준한 업데이트, 지역 리그를 결합해 세계 최대 e스포츠 중 하나가 된 MOBA", description: "League of Legends는 다섯 명이 역할을 나눠 상대 기지를 파괴하는 팀 전략 게임입니다. 무료 플레이와 계속 추가되는 챔피언, 짧고 반복 가능한 경기 구조를 바탕으로 세계 각지의 서버와 프로 리그를 성장시켰습니다.", significance: "게임 업데이트, 방송, 지역 리그와 세계대회를 하나의 장기 생태계로 묶어 라이브 서비스와 e스포츠 운영의 새로운 표준을 만들었습니다.", legacy: "게임을 넘어 음악, 애니메이션, 다른 장르의 작품으로 세계관을 확장하며 하나의 글로벌 엔터테인먼트 IP로 남아 있습니다.", highlights: ["2009년 오픈 베타", "5대5 MOBA", "글로벌 리그와 라이브 서비스"], source: { label: "League of Legends 공식 게임 소개", url: "https://www.leagueoflegends.com/en-us/how-to-play/" }, accent: "#167b93" },
  { year: 2010, name: "World of Tanks", studio: "Wargaming", genre: "차량 전투 MMO", platform: "Windows", milestone: "오픈 베타·CIS 출시", eyebrow: "전차 전투의 대중화", summary: "짧은 팀 대전과 수백 종의 전차 수집을 결합해 글로벌 무료 게임 시장을 넓힌 작품", description: "World of Tanks는 서로 다른 국가와 시대의 전차를 선택해 팀 단위 전투를 벌이는 온라인 액션 게임입니다. 조작은 비교적 단순하게 만들면서 장갑과 관통, 위치 선정의 깊이를 남겨 역사 소재를 대중적인 경쟁 게임으로 바꿨습니다.", significance: "무료 플레이, 짧은 세션, 장기적인 차량 연구를 결합한 운영으로 동유럽 개발사의 게임이 세계 시장을 장악할 수 있음을 보여줬습니다.", legacy: "콘솔과 모바일, 다른 함선·항공 전투 작품으로 확장됐으며 차량 수집형 온라인 게임의 대표적인 모델로 남아 있습니다.", highlights: ["2010년 공개 테스트", "팀 기반 전차 전투", "글로벌 무료 플레이 성공"], source: { label: "Wargaming 공식 20주년 기록", url: "https://worldoftanks.eu/en/news/general-news/wargaming-20th-anniversary/" }, accent: "#6e745a" },
  { year: 2011, name: "Minecraft", studio: "Mojang", genre: "샌드박스", platform: "Windows, Mac OS, Linux", milestone: "베타 종료·1.0 출시", eyebrow: "블록으로 만드는 무한한 세계", summary: "채집과 건축, 생존을 단순한 블록으로 엮어 전 세계의 창작 도구가 된 샌드박스", description: "Minecraft는 블록으로 이루어진 세계에서 자원을 모으고 집과 기계를 만들며 살아가는 샌드박스 게임입니다. 정해진 목표보다 이용자의 상상과 공유를 중심에 두어 어린이부터 전문 창작자까지 각자의 놀이를 만들게 했습니다.", significance: "개발 중 버전을 판매하고 이용자 반응으로 계속 발전시키는 방식과 영상·모드 커뮤니티의 결합은 독립 게임 유통의 흐름을 바꿨습니다.", legacy: "교육용 버전, 대형 서버, 영상 콘텐츠와 공식 마켓으로 확장돼 게임이면서 동시에 제작 도구이자 사회적 공간으로 남아 있습니다.", highlights: ["2011년 1.0 정식 공개", "절차 생성 블록 세계", "창작·교육·영상 문화"], source: { label: "Xbox Wire Minecraft 15주년 기록", url: "https://news.xbox.com/en-us/2024/05/17/minecraft-15-years-most-important-moments/" }, accent: "#5d7f45" },
  { year: 2012, name: "Diablo III", studio: "Blizzard Entertainment", genre: "액션 RPG", platform: "Windows, Mac OS", milestone: "오픈 베타·정식 출시", eyebrow: "액션 RPG의 온라인 전환", summary: "빠른 전투와 온라인 기반 운영으로 대규모 이용자를 다시 던전 파밍에 모은 액션 RPG", description: "Diablo III는 전작의 전리품 수집과 캐릭터 빌드를 더 빠른 전투와 온라인 환경으로 옮긴 액션 RPG입니다. 2012년 공개 베타와 세계 동시 출시는 장르의 높은 기대를 보여줬고, 이후 업데이트를 통해 성장 구조를 크게 재정비했습니다.", significance: "대형 패키지 게임이 출시 이후 시스템을 지속적으로 바꾸고 확장팩과 시즌으로 장기 운영되는 과정을 대표적으로 보여줬습니다.", legacy: "모험 모드와 시즌 여정, 균열 중심 파밍은 후속 액션 RPG의 반복 콘텐츠와 라이브 운영 방식에 직접 이어졌습니다.", highlights: ["2012년 공개 베타", "온라인 협동 액션 RPG", "시즌·균열 중심 장기 운영"], source: { label: "Blizzard 공식 출시 발표", url: "https://news.blizzard.com/en-gb/article/10039616/diablo-iii-launching-may-15-digital-pre-sales-now-open" }, accent: "#8f352d" },
  { year: 2013, name: "Dota 2", studio: "Valve", genre: "MOBA", platform: "Windows, Mac OS, Linux", milestone: "베타 종료·정식 출시", eyebrow: "커뮤니티와 상금이 키운 MOBA", summary: "깊은 팀 전략과 Steam 생태계, 대규모 국제대회로 경쟁 게임의 규모를 확장한 MOBA", description: "Dota 2는 각기 다른 영웅을 선택한 두 팀이 복잡한 지형과 자원, 아이템을 활용해 상대 본진을 무너뜨리는 MOBA입니다. 긴 베타 기간 동안 커뮤니티와 함께 완성도를 높이고 Steam을 통해 세계에 무료로 배포됐습니다.", significance: "게임 안에서 대회 상금을 공동 조성하는 방식과 관전 기능을 결합해 e스포츠가 게임 서비스 자체와 함께 성장할 수 있음을 보여줬습니다.", legacy: "매년 열리는 The International과 커뮤니티 제작 콘텐츠, 계속 변화하는 메타를 통해 가장 깊이 있는 경쟁 게임 중 하나로 남아 있습니다.", highlights: ["2년간의 공개 베타", "The International", "Steam 기반 무료 MOBA"], source: { label: "Steam 공식 제품 페이지", url: "https://store.steampowered.com/app/570/Dota_2/" }, accent: "#a44334" },
  { year: 2014, name: "Hearthstone", studio: "Blizzard Entertainment", genre: "디지털 카드 게임", platform: "Windows, Mac OS, iOS, Android", milestone: "오픈 베타·정식 출시", eyebrow: "카드 게임을 터치 화면으로", summary: "짧은 경기와 직관적인 연출로 디지털 수집형 카드 게임을 대중화한 작품", description: "Hearthstone은 Warcraft 세계의 캐릭터와 주문을 카드로 구성해 대전하는 디지털 카드 게임입니다. 복잡한 계산을 자동 처리하고 명확한 애니메이션과 짧은 경기 시간을 제공해 카드 게임 경험을 PC와 태블릿, 휴대전화로 넓혔습니다.", significance: "무료 진입, 카드 팩, 정기 확장팩과 랭크전을 결합한 운영은 이후 수많은 디지털 카드 게임이 따르는 사업·콘텐츠 구조가 됐습니다.", legacy: "본편뿐 아니라 Battlegrounds 같은 새로운 모드를 더하며 하나의 클라이언트 안에서 카드 기반 전략 경험을 계속 확장하고 있습니다.", highlights: ["2014년 오픈 베타", "모바일 친화적 카드 대전", "디지털 CCG 대중화"], source: { label: "Hearthstone 공식 오픈 베타 발표", url: "https://hearthstone.blizzard.com/en-gb/blog/12440010/" }, accent: "#c78b36" },
  { year: 2015, name: "Rocket League", studio: "Psyonix", genre: "스포츠 액션", platform: "Windows, PlayStation 4", milestone: "베타·정식 출시", eyebrow: "자동차로 하는 축구", summary: "한 문장으로 이해되는 규칙과 높은 숙련도를 결합해 세계적인 경쟁 스포츠가 된 작품", description: "Rocket League는 로켓 엔진을 단 자동차로 거대한 공을 상대 골문에 넣는 스포츠 액션 게임입니다. 규칙은 즉시 이해할 수 있지만 공중 조작과 팀 전술의 깊이가 커서 친구와 즐기는 파티 게임과 전문 e스포츠를 동시에 만족시켰습니다.", significance: "단순한 핵심 규칙, 짧은 경기, 높은 실력 상한이라는 조합이 새로운 경쟁 게임도 전통 스포츠처럼 관전되고 학습될 수 있음을 보여줬습니다.", legacy: "무료 플레이 전환과 크로스 플랫폼 경쟁, 글로벌 리그를 통해 여러 기기의 이용자가 함께하는 스포츠형 라이브 서비스로 발전했습니다.", highlights: ["자동차와 축구의 결합", "짧고 깊은 경쟁전", "크로스 플랫폼 e스포츠"], source: { label: "Rocket League 공식 기념 기록", url: "https://www.rocketleague.com/news/rocket-league-anniversary-update-july-5?lang=en" }, accent: "#267db8" },
  { year: 2016, name: "Overwatch", studio: "Blizzard Entertainment", genre: "히어로 슈터", platform: "Windows, PlayStation 4, Xbox One", milestone: "글로벌 오픈 베타·정식 출시", eyebrow: "영웅이 된 팀 기반 FPS", summary: "다양한 영웅과 역할 조합, 밝은 세계관으로 히어로 슈터를 세계적인 장르로 만든 작품", description: "Overwatch는 고유한 무기와 기술을 가진 영웅을 골라 목표를 수행하는 팀 기반 FPS입니다. 조준 능력뿐 아니라 역할 조합과 궁극기 연계, 전장의 판단을 강조하며 서로 다른 플레이 성향의 이용자를 한 팀에 모았습니다.", significance: "2016년 글로벌 오픈 베타로 대중의 관심을 집중시키고 캐릭터 중심 서사와 경쟁 슈팅을 결합해 히어로 슈터의 전성기를 열었습니다.", legacy: "후속작 Overwatch 2로 서비스가 전환됐으며 역할 고정, 시즌 콘텐츠, 캐릭터 중심 라이브 운영은 여러 팀 기반 게임에 영향을 줬습니다.", highlights: ["2016년 글로벌 오픈 베타", "역할 기반 영웅 조합", "히어로 슈터 대중화"], source: { label: "Overwatch 공식 오픈 베타 발표", url: "https://overwatch.blizzard.com/blog/20100169/" }, accent: "#e69138" },
  { year: 2017, name: "Fortnite Battle Royale", studio: "Epic Games", genre: "배틀로얄", platform: "Windows, Mac, PlayStation 4, Xbox One", milestone: "무료 얼리 액세스", eyebrow: "게임 안에 모인 대중문화", summary: "건축과 100인 생존, 빠른 시즌 변화를 결합해 세계적인 문화 플랫폼이 된 배틀로얄", description: "Fortnite Battle Royale은 100명이 한 섬에서 자원을 모으고 건축하며 마지막 생존자가 되는 게임입니다. 무료 공개와 밝은 미술, 짧은 시즌마다 바뀌는 지도와 협업 이벤트를 통해 게임을 계속 방문하는 문화 공간으로 만들었습니다.", significance: "배틀패스, 시즌 서사, 유명 브랜드와 공연을 게임 안에 결합해 라이브 서비스가 콘텐츠 유통과 사회적 만남의 플랫폼이 될 수 있음을 보여줬습니다.", legacy: "배틀로얄을 넘어 LEGO, 레이싱, 음악과 사용자 제작 경험이 공존하는 플랫폼으로 확장되며 게임의 경계를 계속 넓히고 있습니다.", highlights: ["2017년 무료 공개", "건축이 결합된 배틀로얄", "시즌·공연·브랜드 협업"], source: { label: "Epic Games 무료 공개 발표", url: "https://www.fortnite.com/news/fortnite-battle-royale-goes-free?lang=en-US" }, accent: "#6d63cb" },
  { year: 2018, name: "Among Us", studio: "Innersloth", genre: "소셜 디덕션", platform: "iOS, Android, Windows", milestone: "모바일 정식 출시", eyebrow: "대화가 곧 플레이", summary: "간단한 임무와 거짓말, 추리를 결합해 스트리밍 시대의 세계적 놀이가 된 게임", description: "Among Us는 우주선의 승무원 사이에 숨어든 임포스터를 대화와 투표로 찾아내는 소셜 디덕션 게임입니다. 조작과 규칙은 단순하지만 사람의 말과 행동이 매번 다른 이야기를 만들어 친구 모임과 방송에 잘 어울렸습니다.", significance: "출시 당시보다 2020년 스트리밍과 팬 콘텐츠를 통해 폭발적으로 성장하며 작은 독립 게임도 커뮤니티가 발견하면 세계적 현상이 될 수 있음을 보여줬습니다.", legacy: "여러 플랫폼과 새로운 맵, 역할, 애니메이션으로 확장됐고 온라인에서 함께 말하고 의심하는 파티 게임의 대표작으로 남아 있습니다.", highlights: ["소셜 디덕션 대중화", "스트리밍을 통한 역주행", "3인 개발팀의 글로벌 성공"], source: { label: "Innersloth 공식 프레스 키트", url: "https://www.innersloth.com/press-kit-among-us/" }, accent: "#c94949" },
  { year: 2019, name: "Apex Legends", studio: "Respawn Entertainment", genre: "배틀로얄 FPS", platform: "Windows, PlayStation 4, Xbox One", milestone: "글로벌 기습 출시", eyebrow: "분대 중심 배틀로얄", summary: "영웅 능력과 부드러운 이동, 핑 시스템으로 팀 배틀로얄의 기준을 높인 작품", description: "Apex Legends는 세 명이 분대를 이루고 각기 다른 능력을 가진 레전드로 싸우는 배틀로얄 FPS입니다. 사전 장기 홍보 없이 공개와 동시에 출시됐으며 빠른 이동과 부활, 음성 없이도 협력할 수 있는 정교한 핑 시스템으로 주목받았습니다.", significance: "캐릭터 역할과 배틀로얄을 자연스럽게 결합하고 접근성 높은 비언어 소통을 제시해 팀 기반 온라인 게임의 사용자 경험을 발전시켰습니다.", legacy: "지속적인 시즌과 e스포츠, 콘솔·PC 간 크로스 플레이를 통해 빠른 전투를 선호하는 대표 배틀로얄로 자리 잡았습니다.", highlights: ["2019년 기습 글로벌 출시", "분대와 영웅 능력", "혁신적인 핑 시스템"], source: { label: "EA 공식 출시 발표", url: "https://news.ea.com/press-releases/press-releases-details/2019/Respawn-Launches-Apex-Legends-a-Free-to-Play-Battle-Royale-Experience-Available-Now-on-PC-PS4-and-Xbox-One/default.aspx" }, accent: "#b24a3d" },
  { year: 2020, name: "VALORANT", studio: "Riot Games", genre: "전술 히어로 FPS", platform: "Windows", milestone: "클로즈드 베타·글로벌 출시", eyebrow: "전술 FPS와 영웅 능력의 결합", summary: "정밀한 사격과 요원 능력, 글로벌 서버 인프라를 결합해 새로운 e스포츠 축이 된 FPS", description: "VALORANT는 다섯 명이 공격과 수비로 나뉘어 정밀한 사격과 요원별 능력을 함께 사용하는 전술 FPS입니다. 2020년 스트리밍 연계 베타로 관심을 모은 뒤 낮은 지연 시간과 경쟁 무결성을 강조하며 세계 여러 지역에 출시됐습니다.", significance: "전통적인 전술 FPS의 명확한 교전과 히어로 게임의 능력 조합을 절제해 결합하고, 출시 초기부터 지역별 프로 리그를 설계했습니다.", legacy: "VCT와 Game Changers를 중심으로 글로벌 e스포츠를 확장했으며 콘솔 버전까지 더해 장기 경쟁 플랫폼으로 발전하고 있습니다.", highlights: ["2020년 글로벌 베타", "5대5 전술·요원 조합", "VCT 글로벌 e스포츠"], source: { label: "Riot Games 공식 베타 발표", url: "https://playvalorant.com/en-us/news/announcements/the-valorant-closed-beta-starts-april-7/" }, accent: "#d94f59" },
];

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const existingIds: Record<string, string> = {
  "1998:StarCraft": "milestone-1998-starcraft",
  "1999:EverQuest": "milestone-1999-everquest",
  "2004:World of Warcraft": "milestone-2004-world-of-warcraft",
};

export const gameCatalog: CatalogItem[] = games.map((game) => {
  const key = `${game.year}:${game.name.toLowerCase()}` as keyof typeof gameImages;
  const image = gameImages[key];
  return {
    id: existingIds[`${game.year}:${game.name}`] ?? `game-${game.year}-${slugify(game.name)}`,
    kind: "game",
    slug: slugify(game.name),
    name: game.name,
    brand: game.studio,
    year: game.year,
    activeYears: [game.year],
    eyebrow: game.eyebrow,
    summary: game.summary,
    description: game.description,
    tags: ["게임", game.genre, game.studio, String(game.year), game.milestone],
    accent: game.accent,
    featured: [1998, 2004, 2009, 2011, 2016, 2017, 2020].includes(game.year),
    specs: { 개발사: game.studio, 장르: game.genre, 플랫폼: game.platform, "공개 단계": game.milestone },
    highlights: game.highlights,
    source: game.source,
    image,
    story: { significance: game.significance, legacy: game.legacy },
  } satisfies CatalogItem & { story: { significance: string; legacy: string } };
});

export const gameYears = games.map((game) => game.year);
