"use client";
import { FormEvent, useState } from "react";
import { LoaderCircle, Save } from "lucide-react";
export function ContentForm() {
  const [state, setState] = useState<"idle"|"saving"|"saved"|"error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("saving"); const form = event.currentTarget; const data = new FormData(form); const file = data.get("media"); let mediaKey: string | undefined; if (file instanceof File && file.size) { const upload = new FormData(); upload.set("file", file); const uploaded = await fetch("/api/media", { method:"POST", body:upload }); if (!uploaded.ok) { setState("error"); return; } mediaKey = (await uploaded.json()).key; } const response = await fetch("/api/catalog", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ type:data.get("type"), name:data.get("name"), slug:data.get("slug"), startYear:Number(data.get("startYear")), summary:data.get("summary"), body:`${data.get("body") ?? ""}${mediaKey ? `\nmedia:${mediaKey}` : ""}`, accent:data.get("accent"), status:data.get("status") }) }); setState(response.ok ? "saved" : "error"); if (response.ok) form.reset(); }
  return <form className="admin-form" onSubmit={submit}><div className="form-grid"><label>유형<select name="type"><option value="website">웹사이트</option><option value="phone">휴대폰</option><option value="service">서비스</option></select></label><label>상태<select name="status"><option value="draft">초안</option><option value="review">검토</option><option value="published">공개</option></select></label></div><div className="form-grid"><label>이름<input name="name" required placeholder="싸이월드" /></label><label>고유 주소<input name="slug" required pattern="[a-z0-9-]+" placeholder="cyworld" /></label></div><div className="form-grid"><label>연도<input name="startYear" type="number" required defaultValue="2004" /></label><label>포인트 색<input name="accent" type="color" defaultValue="#9bcbe2" /></label></div><label>한 줄 설명<input name="summary" maxLength={300} /></label><label>상세 설명<textarea name="body" rows={6} /></label><label>이미지<input name="media" type="file" accept="image/jpeg,image/png,image/webp,image/avif" /><small>R2 · 최대 10MB</small></label><button className="admin-save" disabled={state === "saving"}>{state === "saving" ? <LoaderCircle className="spin" /> : <Save />}저장하기</button>{state === "saved" && <p className="success">저장했습니다.</p>}{state === "error" && <p className="error">로컬 D1/R2 연결 또는 입력값을 확인하세요.</p>}</form>;
}

